// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

fn main() {
    let mut __rt = Runtime::new();
    let mut i: f64 = 0.0;

    let mut __pc: u32 = 10;
    '__sm: loop {
        match __pc {
            10 => {
                i = 1.0f64;
                let __for_to_i: f64 = 100.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
                    // line 20
                    if qb_mod(i, 15.0f64) == 0.0f64 {
                        __rt.println(&[qb_str(&("FizzBuzz"))]);
                        { __pc = 60; continue '__sm; }
                    }
                    // line 30
                    if qb_mod(i, 3.0f64) == 0.0f64 {
                        __rt.println(&[qb_str(&("Fizz"))]);
                        { __pc = 60; continue '__sm; }
                    }
                    // line 40
                    if qb_mod(i, 5.0f64) == 0.0f64 {
                        __rt.println(&[qb_str(&("Buzz"))]);
                        { __pc = 60; continue '__sm; }
                    }
                    // line 50
                    __rt.println(&[qb_print_num(i)]);
                    // line 60
                    i += __for_step_i;
                }
                __pc = 70; continue '__sm;
            }
            70 => {
                __rt.quit();
                break '__sm;
            }
            _ => break,
        }
    }
}
