// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

#[derive(Default)]
struct GameState {
    wr: f64,
}

fn lbl_700(__rt: &mut Runtime, __gs: &mut GameState) {
    // label: 710
    __rt.println(&[qb_str(&(" +----+"))]);
    // label: 720
    __rt.println(&[qb_str(&(" |"))]);
    // label: 730
    if qb_bool(qb_from_bool(__gs.wr >= 1_f64)) {
        __rt.println(&[qb_str(&(" |    O"))]);
    } else {
        __rt.println(&[qb_str(&(" |"))]);
    }
    // label: 740
    if qb_bool(qb_from_bool(__gs.wr == 2_f64)) {
        __rt.println(&[qb_str(&(" |    |"))]);
    } else {
        if qb_bool(qb_from_bool(__gs.wr == 3_f64)) {
            __rt.println(&[qb_str(&(" |   /|"))]);
        } else {
            if qb_bool(qb_from_bool(__gs.wr >= 4_f64)) {
                __rt.println(&[qb_str(&(" |   /|\\"))]);
            } else {
                __rt.println(&[qb_str(&(" |"))]);
            }
        }
    }
    // label: 750
    if qb_bool(qb_from_bool(__gs.wr == 5_f64)) {
        __rt.println(&[qb_str(&(" |   /"))]);
    } else {
        if qb_bool(qb_from_bool(__gs.wr >= 6_f64)) {
            __rt.println(&[qb_str(&(" |   / \\"))]);
        } else {
            __rt.println(&[qb_str(&(" |"))]);
        }
    }
    // label: 760
    __rt.println(&[qb_str(&("_|_"))]);
    // label: 770
    return;
}

fn main() {
    let mut __rt = Runtime::new();
    let mut __gs = GameState::default();

    let mut wd_s: String = String::new();
    let mut gs_s: String = String::new();
    let mut mx: f64 = 0.0_f64;
    let mut ok: f64 = 0.0_f64;
    let mut i: f64 = 0.0_f64;
    let mut l_s: String = String::new();
    let mut g_s: String = String::new();
    let mut a_s: String = String::new();

    let mut w_s: Vec<String> = Vec::new();
    let mut __pc: u32 = 10;
    '__sm: loop {
        match __pc {
            10 => {
                __rt.cls(0u8);
                __pc = 20; continue '__sm;
            }
            20 => {
                __rt.randomize(qb_timer());
                __pc = 30; continue '__sm;
            }
            30 => {
                w_s = vec![Default::default(); (10_f64+1.0) as usize];
                __pc = 40; continue '__sm;
            }
            40 => {
                w_s[(1_f64) as usize] = ("COMPUTER").to_string();
                __pc = 50; continue '__sm;
            }
            50 => {
                w_s[(2_f64) as usize] = ("KEYBOARD").to_string();
                __pc = 60; continue '__sm;
            }
            60 => {
                w_s[(3_f64) as usize] = ("PROGRAM").to_string();
                __pc = 70; continue '__sm;
            }
            70 => {
                w_s[(4_f64) as usize] = ("DATABASE").to_string();
                __pc = 80; continue '__sm;
            }
            80 => {
                w_s[(5_f64) as usize] = ("NETWORK").to_string();
                __pc = 90; continue '__sm;
            }
            90 => {
                w_s[(6_f64) as usize] = ("MONITOR").to_string();
                __pc = 100; continue '__sm;
            }
            100 => {
                w_s[(7_f64) as usize] = ("PYTHON").to_string();
                __pc = 110; continue '__sm;
            }
            110 => {
                w_s[(8_f64) as usize] = ("RUST").to_string();
                __pc = 120; continue '__sm;
            }
            120 => {
                w_s[(9_f64) as usize] = ("GWBASIC").to_string();
                __pc = 130; continue '__sm;
            }
            130 => {
                w_s[(10_f64) as usize] = ("PRINTER").to_string();
                __pc = 140; continue '__sm;
            }
            140 => {
                wd_s = (w_s[((qb_int((__rt.rnd() * 10_f64)) + 1_f64)) as usize]).to_string();
                __pc = 150; continue '__sm;
            }
            150 => {
                gs_s = ("").to_string();
                __pc = 160; continue '__sm;
            }
            160 => {
                __gs.wr = 0_f64;
                __pc = 170; continue '__sm;
            }
            170 => {
                mx = 6_f64;
                __pc = 180; continue '__sm;
            }
            180 => {
                __rt.cls(0u8);
                __pc = 190; continue '__sm;
            }
            190 => {
                __rt.println(&[qb_str(&("======================="))]);
                __pc = 200; continue '__sm;
            }
            200 => {
                __rt.println(&[qb_str(&("        HANGMAN"))]);
                __pc = 210; continue '__sm;
            }
            210 => {
                __rt.println(&[qb_str(&("======================="))]);
                __pc = 220; continue '__sm;
            }
            220 => {
                __rt.println(&[]);
                __pc = 230; continue '__sm;
            }
            230 => {
                lbl_700(&mut __rt, &mut __gs);
                __pc = 240; continue '__sm;
            }
            240 => {
                __rt.println(&[]);
                __pc = 250; continue '__sm;
            }
            250 => {
                __rt.print(&[qb_str(&("Word: "))]);
                __pc = 260; continue '__sm;
            }
            260 => {
                ok = 1_f64;
                __pc = 270; continue '__sm;
            }
            270 => {
                i = 1_f64;
                let __for_to_i: f64 = qb_len(&(wd_s));
                let __for_step_i: f64 = 1.0_f64;
                while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
                    // line 280
                    l_s = (qb_mid(&(wd_s), i, Some(1_f64))).to_string();
                    // line 290
                    if qb_bool(qb_from_bool(qb_instr(1.0, &(gs_s), &(l_s)) > 0_f64)) {
                        __rt.print(&[qb_str(&(l_s)), qb_str(&(" "))]);
                    } else {
                        __rt.print(&[qb_str(&("_ "))]);
                        ok = 0_f64;
                    }
                    // line 300
                    i += __for_step_i;
                }
                __pc = 310; continue '__sm;
            }
            310 => {
                __rt.println(&[]);
                __pc = 320; continue '__sm;
            }
            320 => {
                __rt.println(&[]);
                __pc = 330; continue '__sm;
            }
            330 => {
                __rt.print(&[qb_str(&("Guessed: "))]);
                __pc = 340; continue '__sm;
            }
            340 => {
                i = 1_f64;
                let __for_to_i: f64 = qb_len(&(gs_s));
                let __for_step_i: f64 = 1.0_f64;
                while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
                    // line 350
                    __rt.print(&[qb_str(&(qb_mid(&(gs_s), i, Some(1_f64)))), qb_str(&(" "))]);
                    // line 360
                    i += __for_step_i;
                }
                __pc = 370; continue '__sm;
            }
            370 => {
                __rt.println(&[]);
                __pc = 380; continue '__sm;
            }
            380 => {
                __rt.println(&[]);
                __pc = 390; continue '__sm;
            }
            390 => {
                __rt.println(&[qb_str(&("Wrong:")), qb_print_num(__gs.wr), qb_str(&("/")), qb_print_num(mx)]);
                __pc = 400; continue '__sm;
            }
            400 => {
                __rt.println(&[]);
                __pc = 410; continue '__sm;
            }
            410 => {
                if qb_bool(ok) {
                    __rt.println(&[qb_str(&("YOU WIN!"))]);
                    { __pc = 660; continue '__sm; }
                }
                __pc = 420; continue '__sm;
            }
            420 => {
                if qb_bool(qb_from_bool(__gs.wr >= mx)) {
                    __rt.println(&[qb_str(&("YOU LOSE! Word was: ")), qb_str(&(wd_s))]);
                    { __pc = 660; continue '__sm; }
                }
                __pc = 430; continue '__sm;
            }
            430 => {
                __rt.print_str("Letter: ? ");
                g_s = __rt.input_line();
                __pc = 440; continue '__sm;
            }
            440 => {
                if qb_bool(qb_from_bool(qb_len(&(g_s)) == 0_f64)) {
                    { __pc = 180; continue '__sm; }
                }
                __pc = 450; continue '__sm;
            }
            450 => {
                g_s = (qb_ucase(&(qb_left(&(g_s), 1_f64)))).to_string();
                __pc = 460; continue '__sm;
            }
            460 => {
                if qb_bool(qb_or(qb_from_bool((g_s).as_str() < "A"), qb_from_bool((g_s).as_str() > "Z"))) {
                    __rt.println(&[qb_str(&("A-Z only!"))]);
                    __rt.sleep(2_f64);
                    { __pc = 180; continue '__sm; }
                }
                __pc = 470; continue '__sm;
            }
            470 => {
                if qb_bool(qb_from_bool(qb_instr(1.0, &(gs_s), &(g_s)) > 0_f64)) {
                    __rt.println(&[qb_str(&("Already guessed!"))]);
                    __rt.sleep(2_f64);
                    { __pc = 180; continue '__sm; }
                }
                __pc = 480; continue '__sm;
            }
            480 => {
                gs_s = (format!("{}{}" ,gs_s,g_s)).to_string();
                __pc = 490; continue '__sm;
            }
            490 => {
                if qb_bool(qb_from_bool(qb_instr(1.0, &(wd_s), &(g_s)) == 0_f64)) {
                    __gs.wr = (__gs.wr + 1_f64);
                }
                __pc = 500; continue '__sm;
            }
            500 => {
                { __pc = 180; continue '__sm; }
                __pc = 660; continue '__sm;
            }
            660 => {
                __rt.println(&[]);
                __pc = 670; continue '__sm;
            }
            670 => {
                __rt.println(&[qb_str(&("Press ENTER to quit..."))]);
                __pc = 680; continue '__sm;
            }
            680 => {
                a_s = __rt.input_line();
                __pc = 690; continue '__sm;
            }
            690 => {
                __rt.quit();
                break '__sm;
            }
            _ => break,
        }
    }
}
