// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

fn main() {
    let mut __rt = Runtime::new();
    __rt.apply_behavioral_env();
    let mut a: f64 = 0.0;

    // label: 5
    // label: 10
    __rt.println(&[qb_str(&("HELLO WORLD!!"))]);
    // label: 15
    a = 1.0f64;
    // label: 20
    a = (a + 1.0f64);
    // label: 20
    __rt.println(&[qb_print_num(a)]);
    // label: 30
    __rt.println(&[qb_str(&("GOOD BYE!"))]);
}
