// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

static __DATA: &[&str] = &["ALPHA", "BETA", "GAMMA", "DELTA", "OMEGA"];
static __DATA_PTR: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

#[derive(Default)]
struct GameState {
    a: String,
    i: f64,
}

fn fnsq(__rt: &mut Runtime, __gs: &mut GameState, mut x: f64) -> f64 {
    (x * x)
}

fn fndb(__rt: &mut Runtime, __gs: &mut GameState, mut x: f64) -> f64 {
    (x * 2.0f64)
}

fn lbl_5100(__rt: &mut Runtime, __gs: &mut GameState) {
    __rt.println(&[qb_str(&("SUB 1"))]);
    // label: 5110
    return;
}

fn lbl_5200(__rt: &mut Runtime, __gs: &mut GameState) {
    __rt.println(&[qb_str(&("SUB 2"))]);
    // label: 5210
    return;
}

fn lbl_5300(__rt: &mut Runtime, __gs: &mut GameState) {
    __rt.println(&[qb_str(&("SUB 3"))]);
    // label: 5310
    return;
}

fn lbl_5400(__rt: &mut Runtime, __gs: &mut GameState) {
    __rt.println(&[qb_str(&("SUB 4"))]);
    // label: 5410
    return;
}

fn lbl_7200(__rt: &mut Runtime, __gs: &mut GameState) {
    __rt.println(&[qb_str(&("CALL ")), qb_print_num(__gs.i)]);
    // label: 7210
    return;
}

fn lbl_9500(__rt: &mut Runtime, __gs: &mut GameState) {
    let a_s: String = String::new();

    __rt.println(&[]);
    // label: 9510
    __rt.println(&[qb_str(&("PRESS ENTER"))]);
    // label: 9520
    __gs.a = __rt.input_line();
    // label: 9530
    return;
}

fn main() {
    let mut __rt = Runtime::new();
    let mut __gs = GameState::default();

    let mut c: f64 = 0.0;
    let a_s: String = String::new();
    let mut x1: f64 = 0.0;
    let mut y1: f64 = 0.0;
    let mut x2: f64 = 0.0;
    let mut y2: f64 = 0.0;
    let mut x: f64 = 0.0;
    let mut s: f64 = 0.0;

    let mut n: Vec<f64> = Vec::new();
    let mut name_s: Vec<String> = Vec::new();
    let mut __pc: u32 = 10;
    '__sm: loop {
        match __pc {
            10 => {
                __rt.cls(0u8);
                __pc = 20; continue '__sm;
            }
            20 => {
                __rt.println(&[qb_str(&("GW-BASIC MEGA TEST"))]);
                __pc = 30; continue '__sm;
            }
            30 => {
                __rt.println(&[qb_str(&(qb_string_s(40.0f64, "=")))]);
                __pc = 40; continue '__sm;
            }
            40 => {
                n = vec![Default::default(); (10.0f64+1.0) as usize];
                __pc = 50; continue '__sm;
            }
            50 => {
                name_s = vec![Default::default(); (5.0f64+1.0) as usize];
                __pc = 60; continue '__sm;
            }
            60 => {
                __pc = 70; continue '__sm;
            }
            70 => {
                __gs.i = 1.0f64;
                let __for_to_i: f64 = 5.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && __gs.i <= __for_to_i) || (__for_step_i < 0.0 && __gs.i >= __for_to_i) {
                    // line 80
                    name_s[(__gs.i) as usize] = qb_read_data(&__DATA, &__DATA_PTR).parse().unwrap_or_default();
                    // line 90
                    __gs.i += __for_step_i;
                }
                __pc = 100; continue '__sm;
            }
            100 => {
                __gs.i = 1.0f64;
                let __for_to_i: f64 = 10.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && __gs.i <= __for_to_i) || (__for_step_i < 0.0 && __gs.i >= __for_to_i) {
                    // line 110
                    n[(__gs.i) as usize] = (__gs.i * __gs.i);
                    // line 120
                    __gs.i += __for_step_i;
                }
                __pc = 130; continue '__sm;
            }
            130 => {
                __pc = 140; continue '__sm;
            }
            140 => {
                __pc = 150; continue '__sm;
            }
            150 => {
                __rt.randomize(qb_timer());
                __pc = 160; continue '__sm;
            }
            160 => {
                __rt.println(&[]);
                __pc = 170; continue '__sm;
            }
            170 => {
                __rt.println(&[qb_str(&("MAIN MENU"))]);
                __pc = 180; continue '__sm;
            }
            180 => {
                __rt.println(&[qb_str(&("1 - ARRAY TEST"))]);
                __pc = 190; continue '__sm;
            }
            190 => {
                __rt.println(&[qb_str(&("2 - RANDOM TEST"))]);
                __pc = 200; continue '__sm;
            }
            200 => {
                __rt.println(&[qb_str(&("3 - STRING TEST"))]);
                __pc = 210; continue '__sm;
            }
            210 => {
                __rt.println(&[qb_str(&("4 - GRAPHICS TEST"))]);
                __pc = 220; continue '__sm;
            }
            220 => {
                __rt.println(&[qb_str(&("5 - ON GOTO TEST"))]);
                __pc = 230; continue '__sm;
            }
            230 => {
                __rt.println(&[qb_str(&("6 - DATA TEST"))]);
                __pc = 240; continue '__sm;
            }
            240 => {
                __rt.println(&[qb_str(&("7 - SUBROUTINE TEST"))]);
                __pc = 250; continue '__sm;
            }
            250 => {
                __rt.println(&[qb_str(&("8 - COMPUTE TEST"))]);
                __pc = 260; continue '__sm;
            }
            260 => {
                __rt.println(&[qb_str(&("9 - EXIT"))]);
                __pc = 270; continue '__sm;
            }
            270 => {
                __rt.print_str("CHOICE? ");
                c = __rt.input_line().trim().parse().unwrap_or_default();
                __pc = 280; continue '__sm;
            }
            280 => {
                match qb_cint(c) as i64 {
                    1 => {
                        { __pc = 1000; continue '__sm; }
                    }
                    2 => {
                        { __pc = 2000; continue '__sm; }
                    }
                    3 => {
                        { __pc = 3000; continue '__sm; }
                    }
                    4 => {
                        { __pc = 4000; continue '__sm; }
                    }
                    5 => {
                        { __pc = 5000; continue '__sm; }
                    }
                    6 => {
                        { __pc = 6000; continue '__sm; }
                    }
                    7 => {
                        { __pc = 7000; continue '__sm; }
                    }
                    8 => {
                        { __pc = 8000; continue '__sm; }
                    }
                    9 => {
                        { __pc = 9000; continue '__sm; }
                    }
                    _ => {}
                }
                __pc = 290; continue '__sm;
            }
            290 => {
                { __pc = 160; continue '__sm; }
                __pc = 1000; continue '__sm;
            }
            1000 => {
                __rt.cls(0u8);
                __pc = 1010; continue '__sm;
            }
            1010 => {
                __rt.println(&[qb_str(&("ARRAY TEST"))]);
                __pc = 1020; continue '__sm;
            }
            1020 => {
                __gs.i = 1.0f64;
                let __for_to_i: f64 = 10.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && __gs.i <= __for_to_i) || (__for_step_i < 0.0 && __gs.i >= __for_to_i) {
                    // line 1030
                    __rt.println(&[qb_print_num(__gs.i), qb_print_num(n[(__gs.i) as usize])]);
                    // line 1040
                    __gs.i += __for_step_i;
                }
                __pc = 1050; continue '__sm;
            }
            1050 => {
                lbl_9500(&mut __rt, &mut __gs);
                __pc = 1060; continue '__sm;
            }
            1060 => {
                { __pc = 160; continue '__sm; }
                __pc = 2000; continue '__sm;
            }
            2000 => {
                __rt.cls(0u8);
                __pc = 2010; continue '__sm;
            }
            2010 => {
                __rt.println(&[qb_str(&("RANDOM TEST"))]);
                __pc = 2020; continue '__sm;
            }
            2020 => {
                __gs.i = 1.0f64;
                let __for_to_i: f64 = 20.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && __gs.i <= __for_to_i) || (__for_step_i < 0.0 && __gs.i >= __for_to_i) {
                    // line 2030
                    let __tmp0 = __rt.rnd();
                    __rt.print(&[qb_print_num(qb_int((__tmp0 * 100.0f64)))]);
                    // line 2040
                    __gs.i += __for_step_i;
                }
                __pc = 2050; continue '__sm;
            }
            2050 => {
                __rt.println(&[]);
                __pc = 2060; continue '__sm;
            }
            2060 => {
                lbl_9500(&mut __rt, &mut __gs);
                __pc = 2070; continue '__sm;
            }
            2070 => {
                { __pc = 160; continue '__sm; }
                __pc = 3000; continue '__sm;
            }
            3000 => {
                __rt.cls(0u8);
                __pc = 3010; continue '__sm;
            }
            3010 => {
                __rt.println(&[qb_str(&("STRING TEST"))]);
                __pc = 3020; continue '__sm;
            }
            3020 => {
                __gs.a = ("GWBASICTEST").to_string();
                __pc = 3030; continue '__sm;
            }
            3030 => {
                __rt.println(&[qb_str(&(__gs.a))]);
                __pc = 3040; continue '__sm;
            }
            3040 => {
                __rt.println(&[qb_str(&(qb_left(&(__gs.a), 3.0f64)))]);
                __pc = 3050; continue '__sm;
            }
            3050 => {
                __rt.println(&[qb_str(&(qb_right(&(__gs.a), 4.0f64)))]);
                __pc = 3060; continue '__sm;
            }
            3060 => {
                __rt.println(&[qb_str(&(qb_mid(&(__gs.a), 4.0f64, Some(5.0f64))))]);
                __pc = 3070; continue '__sm;
            }
            3070 => {
                lbl_9500(&mut __rt, &mut __gs);
                __pc = 3080; continue '__sm;
            }
            3080 => {
                { __pc = 160; continue '__sm; }
                __pc = 4000; continue '__sm;
            }
            4000 => {
                __rt.cls(0u8);
                __pc = 4010; continue '__sm;
            }
            4010 => {
                __rt.println(&[qb_str(&("GRAPHICS TEST"))]);
                __pc = 4020; continue '__sm;
            }
            4020 => {
                __rt.screen(1.0f64);
                __pc = 4030; continue '__sm;
            }
            4030 => {
                __gs.i = 1.0f64;
                let __for_to_i: f64 = 100.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && __gs.i <= __for_to_i) || (__for_step_i < 0.0 && __gs.i >= __for_to_i) {
                    // line 4040
                    let __tmp1 = __rt.rnd();
                    x1 = qb_int((__tmp1 * 320.0f64));
                    // line 4050
                    let __tmp2 = __rt.rnd();
                    y1 = qb_int((__tmp2 * 200.0f64));
                    // line 4060
                    let __tmp3 = __rt.rnd();
                    x2 = qb_int((__tmp3 * 320.0f64));
                    // line 4070
                    let __tmp4 = __rt.rnd();
                    y2 = qb_int((__tmp4 * 200.0f64));
                    // line 4080
                    let __tmp5 = __rt.rnd();
                    c = qb_int((__tmp5 * 4.0f64));
                    // line 4090
                    __rt.line(x1,y1,x2,y2,c);
                    // line 4100
                    __gs.i += __for_step_i;
                }
                __pc = 4110; continue '__sm;
            }
            4110 => {
                let __tmp6 = __rt.input_str(1.0f64);
                __gs.a = (__tmp6).to_string();
                __pc = 4120; continue '__sm;
            }
            4120 => {
                __rt.screen(0.0f64);
                __pc = 4130; continue '__sm;
            }
            4130 => {
                { __pc = 160; continue '__sm; }
                __pc = 5000; continue '__sm;
            }
            5000 => {
                __rt.cls(0u8);
                __pc = 5010; continue '__sm;
            }
            5010 => {
                __rt.println(&[qb_str(&("ON GOTO TEST"))]);
                __pc = 5020; continue '__sm;
            }
            5020 => {
                __gs.i = 1.0f64;
                let __for_to_i: f64 = 20.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && __gs.i <= __for_to_i) || (__for_step_i < 0.0 && __gs.i >= __for_to_i) {
                    // line 5030
                    let __tmp7 = __rt.rnd();
                    x = (qb_int((__tmp7 * 4.0f64)) + 1.0f64);
                    // line 5040
                    match qb_cint(x) as i64 {
                        1 => {
                            lbl_5100(&mut __rt, &mut __gs);
                        }
                        2 => {
                            lbl_5200(&mut __rt, &mut __gs);
                        }
                        3 => {
                            lbl_5300(&mut __rt, &mut __gs);
                        }
                        4 => {
                            lbl_5400(&mut __rt, &mut __gs);
                        }
                        _ => {}
                    }
                    // line 5050
                    __gs.i += __for_step_i;
                }
                __pc = 5060; continue '__sm;
            }
            5060 => {
                lbl_9500(&mut __rt, &mut __gs);
                __pc = 5070; continue '__sm;
            }
            5070 => {
                { __pc = 160; continue '__sm; }
                __pc = 6000; continue '__sm;
            }
            6000 => {
                __rt.cls(0u8);
                __pc = 6010; continue '__sm;
            }
            6010 => {
                __rt.println(&[qb_str(&("DATA TEST"))]);
                __pc = 6020; continue '__sm;
            }
            6020 => {
                __DATA_PTR.store(0, std::sync::atomic::Ordering::SeqCst);
                __pc = 6030; continue '__sm;
            }
            6030 => {
                __gs.i = 1.0f64;
                let __for_to_i: f64 = 5.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && __gs.i <= __for_to_i) || (__for_step_i < 0.0 && __gs.i >= __for_to_i) {
                    // line 6040
                    __gs.a = qb_read_data(&__DATA, &__DATA_PTR).parse().unwrap_or_default();
                    // line 6050
                    __rt.println(&[qb_str(&(__gs.a))]);
                    // line 6060
                    __gs.i += __for_step_i;
                }
                __pc = 6070; continue '__sm;
            }
            6070 => {
                lbl_9500(&mut __rt, &mut __gs);
                __pc = 6080; continue '__sm;
            }
            6080 => {
                { __pc = 160; continue '__sm; }
                __pc = 7000; continue '__sm;
            }
            7000 => {
                __rt.cls(0u8);
                __pc = 7010; continue '__sm;
            }
            7010 => {
                __rt.println(&[qb_str(&("SUBROUTINE TEST"))]);
                __pc = 7020; continue '__sm;
            }
            7020 => {
                __gs.i = 1.0f64;
                let __for_to_i: f64 = 5.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && __gs.i <= __for_to_i) || (__for_step_i < 0.0 && __gs.i >= __for_to_i) {
                    // line 7030
                    lbl_7200(&mut __rt, &mut __gs);
                    // line 7040
                    __gs.i += __for_step_i;
                }
                __pc = 7050; continue '__sm;
            }
            7050 => {
                lbl_9500(&mut __rt, &mut __gs);
                __pc = 7060; continue '__sm;
            }
            7060 => {
                { __pc = 160; continue '__sm; }
                __pc = 8000; continue '__sm;
            }
            8000 => {
                __rt.cls(0u8);
                __pc = 8010; continue '__sm;
            }
            8010 => {
                __rt.println(&[qb_str(&("COMPUTE TEST"))]);
                __pc = 8020; continue '__sm;
            }
            8020 => {
                __gs.i = 1.0f64;
                let __for_to_i: f64 = 10.0f64;
                let __for_step_i: f64 = 1.0;
                while (__for_step_i > 0.0 && __gs.i <= __for_to_i) || (__for_step_i < 0.0 && __gs.i >= __for_to_i) {
                    // line 8030
                    __rt.print(&[qb_print_num(__gs.i)]);
                    // line 8040
                    let __fa8 = __gs.i;
                    let __tmp9 = fnsq(&mut __rt, &mut __gs, __fa8);
                    __rt.print(&[qb_print_num(__tmp9)]);
                    // line 8050
                    let __fa10 = __gs.i;
                    let __tmp11 = fndb(&mut __rt, &mut __gs, __fa10);
                    __rt.println(&[qb_print_num(__tmp11)]);
                    // line 8060
                    __gs.i += __for_step_i;
                }
                __pc = 8070; continue '__sm;
            }
            8070 => {
                s = 0.0f64;
                __pc = 8080; continue '__sm;
            }
            8080 => {
                __gs.i = 1.0f64;
                __pc = 8090; continue '__sm;
            }
            8090 => {
                while __gs.i <= 100.0f64 {
                    // line 8100
                    s = (s + __gs.i);
                    // line 8110
                    __gs.i = (__gs.i + 1.0f64);
                    // line 8120
                }
                __pc = 8130; continue '__sm;
            }
            8130 => {
                __rt.println(&[]);
                __pc = 8140; continue '__sm;
            }
            8140 => {
                __rt.println(&[qb_str(&("SUM=")), qb_print_num(s)]);
                __pc = 8150; continue '__sm;
            }
            8150 => {
                lbl_9500(&mut __rt, &mut __gs);
                __pc = 8160; continue '__sm;
            }
            8160 => {
                { __pc = 160; continue '__sm; }
                __pc = 9000; continue '__sm;
            }
            9000 => {
                __rt.cls(0u8);
                __pc = 9010; continue '__sm;
            }
            9010 => {
                __rt.println(&[qb_str(&("GOODBYE"))]);
                __pc = 9020; continue '__sm;
            }
            9020 => {
                __rt.quit();
                break '__sm;
            }
            _ => break,
        }
    }
}
