// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

fn main() {
    let mut __rt = Runtime::new();
    __rt.apply_behavioral_env();
    let mut __pc: u32 = 10;
    '__sm: loop {
        match __pc {
            10 => {
                __rt.println(&[qb_str(&("AT 10"))]);
                { __pc = 50; continue '__sm; }
                __pc = 20; continue '__sm;
            }
            20 => {
                __rt.println(&[qb_str(&("AT 20"))]);
                { __pc = 80; continue '__sm; }
                __pc = 30; continue '__sm;
            }
            30 => {
                __rt.println(&[qb_str(&("AT 30"))]);
                { __pc = 60; continue '__sm; }
                __pc = 40; continue '__sm;
            }
            40 => {
                __rt.println(&[qb_str(&("AT 40"))]);
                { __pc = 100; continue '__sm; }
                __pc = 50; continue '__sm;
            }
            50 => {
                __rt.println(&[qb_str(&("AT 50"))]);
                { __pc = 90; continue '__sm; }
                __pc = 60; continue '__sm;
            }
            60 => {
                __rt.println(&[qb_str(&("AT 60"))]);
                { __pc = 20; continue '__sm; }
                __pc = 70; continue '__sm;
            }
            70 => {
                __rt.println(&[qb_str(&("AT 70"))]);
                { __pc = 30; continue '__sm; }
                __pc = 80; continue '__sm;
            }
            80 => {
                __rt.println(&[qb_str(&("AT 80"))]);
                { __pc = 120; continue '__sm; }
                __pc = 90; continue '__sm;
            }
            90 => {
                __rt.println(&[qb_str(&("AT 90"))]);
                { __pc = 40; continue '__sm; }
                __pc = 100; continue '__sm;
            }
            100 => {
                __rt.println(&[qb_str(&("AT 100"))]);
                { __pc = 140; continue '__sm; }
                __pc = 110; continue '__sm;
            }
            110 => {
                __rt.println(&[qb_str(&("AT 110"))]);
                { __pc = 70; continue '__sm; }
                __pc = 120; continue '__sm;
            }
            120 => {
                __rt.println(&[qb_str(&("AT 120"))]);
                { __pc = 160; continue '__sm; }
                __pc = 130; continue '__sm;
            }
            130 => {
                __rt.println(&[qb_str(&("AT 130"))]);
                { __pc = 110; continue '__sm; }
                __pc = 140; continue '__sm;
            }
            140 => {
                __rt.println(&[qb_str(&("AT 140"))]);
                { __pc = 180; continue '__sm; }
                __pc = 150; continue '__sm;
            }
            150 => {
                __rt.println(&[qb_str(&("AT 150"))]);
                { __pc = 130; continue '__sm; }
                __pc = 160; continue '__sm;
            }
            160 => {
                __rt.println(&[qb_str(&("AT 160"))]);
                { __pc = 200; continue '__sm; }
                __pc = 170; continue '__sm;
            }
            170 => {
                __rt.println(&[qb_str(&("AT 170"))]);
                { __pc = 150; continue '__sm; }
                __pc = 180; continue '__sm;
            }
            180 => {
                __rt.println(&[qb_str(&("AT 180"))]);
                { __pc = 220; continue '__sm; }
                __pc = 190; continue '__sm;
            }
            190 => {
                __rt.println(&[qb_str(&("AT 190"))]);
                { __pc = 170; continue '__sm; }
                __pc = 200; continue '__sm;
            }
            200 => {
                __rt.println(&[qb_str(&("AT 200"))]);
                { __pc = 240; continue '__sm; }
                __pc = 210; continue '__sm;
            }
            210 => {
                __rt.println(&[qb_str(&("AT 210"))]);
                { __pc = 190; continue '__sm; }
                __pc = 220; continue '__sm;
            }
            220 => {
                __rt.println(&[qb_str(&("AT 220"))]);
                { __pc = 260; continue '__sm; }
                __pc = 230; continue '__sm;
            }
            230 => {
                __rt.println(&[qb_str(&("AT 230"))]);
                { __pc = 210; continue '__sm; }
                __pc = 240; continue '__sm;
            }
            240 => {
                __rt.println(&[qb_str(&("AT 240"))]);
                { __pc = 280; continue '__sm; }
                __pc = 250; continue '__sm;
            }
            250 => {
                __rt.println(&[qb_str(&("AT 250"))]);
                { __pc = 230; continue '__sm; }
                __pc = 260; continue '__sm;
            }
            260 => {
                __rt.println(&[qb_str(&("AT 260"))]);
                { __pc = 300; continue '__sm; }
                __pc = 270; continue '__sm;
            }
            270 => {
                __rt.println(&[qb_str(&("AT 270"))]);
                { __pc = 250; continue '__sm; }
                __pc = 280; continue '__sm;
            }
            280 => {
                __rt.println(&[qb_str(&("AT 280"))]);
                { __pc = 320; continue '__sm; }
                __pc = 290; continue '__sm;
            }
            290 => {
                __rt.println(&[qb_str(&("AT 290"))]);
                { __pc = 270; continue '__sm; }
                __pc = 300; continue '__sm;
            }
            300 => {
                __rt.println(&[qb_str(&("AT 300"))]);
                { __pc = 340; continue '__sm; }
                __pc = 310; continue '__sm;
            }
            310 => {
                __rt.println(&[qb_str(&("AT 310"))]);
                { __pc = 290; continue '__sm; }
                __pc = 320; continue '__sm;
            }
            320 => {
                __rt.println(&[qb_str(&("AT 320"))]);
                { __pc = 360; continue '__sm; }
                __pc = 330; continue '__sm;
            }
            330 => {
                __rt.println(&[qb_str(&("AT 330"))]);
                { __pc = 310; continue '__sm; }
                __pc = 340; continue '__sm;
            }
            340 => {
                __rt.println(&[qb_str(&("AT 340"))]);
                { __pc = 380; continue '__sm; }
                __pc = 350; continue '__sm;
            }
            350 => {
                __rt.println(&[qb_str(&("AT 350"))]);
                { __pc = 330; continue '__sm; }
                __pc = 360; continue '__sm;
            }
            360 => {
                __rt.println(&[qb_str(&("AT 360"))]);
                { __pc = 400; continue '__sm; }
                __pc = 370; continue '__sm;
            }
            370 => {
                __rt.println(&[qb_str(&("AT 370"))]);
                { __pc = 350; continue '__sm; }
                __pc = 380; continue '__sm;
            }
            380 => {
                __rt.println(&[qb_str(&("AT 380"))]);
                { __pc = 420; continue '__sm; }
                __pc = 390; continue '__sm;
            }
            390 => {
                __rt.println(&[qb_str(&("AT 390"))]);
                { __pc = 370; continue '__sm; }
                __pc = 400; continue '__sm;
            }
            400 => {
                __rt.println(&[qb_str(&("AT 400"))]);
                { __pc = 440; continue '__sm; }
                __pc = 410; continue '__sm;
            }
            410 => {
                __rt.println(&[qb_str(&("AT 410"))]);
                { __pc = 390; continue '__sm; }
                __pc = 420; continue '__sm;
            }
            420 => {
                __rt.println(&[qb_str(&("AT 420"))]);
                { __pc = 460; continue '__sm; }
                __pc = 430; continue '__sm;
            }
            430 => {
                __rt.println(&[qb_str(&("AT 430"))]);
                { __pc = 410; continue '__sm; }
                __pc = 440; continue '__sm;
            }
            440 => {
                __rt.println(&[qb_str(&("AT 440"))]);
                { __pc = 480; continue '__sm; }
                __pc = 450; continue '__sm;
            }
            450 => {
                __rt.println(&[qb_str(&("AT 450"))]);
                { __pc = 430; continue '__sm; }
                __pc = 460; continue '__sm;
            }
            460 => {
                __rt.println(&[qb_str(&("AT 460"))]);
                { __pc = 500; continue '__sm; }
                __pc = 470; continue '__sm;
            }
            470 => {
                __rt.println(&[qb_str(&("AT 470"))]);
                { __pc = 450; continue '__sm; }
                __pc = 480; continue '__sm;
            }
            480 => {
                __rt.println(&[qb_str(&("AT 480"))]);
                { __pc = 520; continue '__sm; }
                __pc = 490; continue '__sm;
            }
            490 => {
                __rt.println(&[qb_str(&("AT 490"))]);
                { __pc = 470; continue '__sm; }
                __pc = 500; continue '__sm;
            }
            500 => {
                __rt.println(&[qb_str(&("AT 500"))]);
                { __pc = 540; continue '__sm; }
                __pc = 510; continue '__sm;
            }
            510 => {
                __rt.println(&[qb_str(&("AT 510"))]);
                { __pc = 490; continue '__sm; }
                __pc = 520; continue '__sm;
            }
            520 => {
                __rt.println(&[qb_str(&("AT 520"))]);
                { __pc = 560; continue '__sm; }
                __pc = 530; continue '__sm;
            }
            530 => {
                __rt.println(&[qb_str(&("AT 530"))]);
                { __pc = 510; continue '__sm; }
                __pc = 540; continue '__sm;
            }
            540 => {
                __rt.println(&[qb_str(&("AT 540"))]);
                { __pc = 580; continue '__sm; }
                __pc = 550; continue '__sm;
            }
            550 => {
                __rt.println(&[qb_str(&("AT 550"))]);
                { __pc = 530; continue '__sm; }
                __pc = 560; continue '__sm;
            }
            560 => {
                __rt.println(&[qb_str(&("AT 560"))]);
                { __pc = 600; continue '__sm; }
                __pc = 570; continue '__sm;
            }
            570 => {
                __rt.println(&[qb_str(&("AT 570"))]);
                { __pc = 550; continue '__sm; }
                __pc = 580; continue '__sm;
            }
            580 => {
                __rt.println(&[qb_str(&("AT 580"))]);
                { __pc = 620; continue '__sm; }
                __pc = 590; continue '__sm;
            }
            590 => {
                __rt.println(&[qb_str(&("AT 590"))]);
                { __pc = 570; continue '__sm; }
                __pc = 600; continue '__sm;
            }
            600 => {
                __rt.println(&[qb_str(&("AT 600"))]);
                { __pc = 640; continue '__sm; }
                __pc = 610; continue '__sm;
            }
            610 => {
                __rt.println(&[qb_str(&("AT 610"))]);
                { __pc = 590; continue '__sm; }
                __pc = 620; continue '__sm;
            }
            620 => {
                __rt.println(&[qb_str(&("AT 620"))]);
                { __pc = 660; continue '__sm; }
                __pc = 630; continue '__sm;
            }
            630 => {
                __rt.println(&[qb_str(&("AT 630"))]);
                { __pc = 610; continue '__sm; }
                __pc = 640; continue '__sm;
            }
            640 => {
                __rt.println(&[qb_str(&("AT 640"))]);
                { __pc = 680; continue '__sm; }
                __pc = 650; continue '__sm;
            }
            650 => {
                __rt.println(&[qb_str(&("AT 650"))]);
                { __pc = 630; continue '__sm; }
                __pc = 660; continue '__sm;
            }
            660 => {
                __rt.println(&[qb_str(&("AT 660"))]);
                { __pc = 700; continue '__sm; }
                __pc = 670; continue '__sm;
            }
            670 => {
                __rt.println(&[qb_str(&("AT 670"))]);
                { __pc = 650; continue '__sm; }
                __pc = 680; continue '__sm;
            }
            680 => {
                __rt.println(&[qb_str(&("AT 680"))]);
                { __pc = 720; continue '__sm; }
                __pc = 690; continue '__sm;
            }
            690 => {
                __rt.println(&[qb_str(&("AT 690"))]);
                { __pc = 670; continue '__sm; }
                __pc = 700; continue '__sm;
            }
            700 => {
                __rt.println(&[qb_str(&("AT 700"))]);
                { __pc = 740; continue '__sm; }
                __pc = 710; continue '__sm;
            }
            710 => {
                __rt.println(&[qb_str(&("AT 710"))]);
                { __pc = 690; continue '__sm; }
                __pc = 720; continue '__sm;
            }
            720 => {
                __rt.println(&[qb_str(&("AT 720"))]);
                { __pc = 760; continue '__sm; }
                __pc = 730; continue '__sm;
            }
            730 => {
                __rt.println(&[qb_str(&("AT 730"))]);
                { __pc = 710; continue '__sm; }
                __pc = 740; continue '__sm;
            }
            740 => {
                __rt.println(&[qb_str(&("AT 740"))]);
                { __pc = 780; continue '__sm; }
                __pc = 750; continue '__sm;
            }
            750 => {
                __rt.println(&[qb_str(&("AT 750"))]);
                { __pc = 730; continue '__sm; }
                __pc = 760; continue '__sm;
            }
            760 => {
                __rt.println(&[qb_str(&("AT 760"))]);
                { __pc = 800; continue '__sm; }
                __pc = 770; continue '__sm;
            }
            770 => {
                __rt.println(&[qb_str(&("AT 770"))]);
                { __pc = 750; continue '__sm; }
                __pc = 780; continue '__sm;
            }
            780 => {
                __rt.println(&[qb_str(&("AT 780"))]);
                { __pc = 820; continue '__sm; }
                __pc = 790; continue '__sm;
            }
            790 => {
                __rt.println(&[qb_str(&("AT 790"))]);
                { __pc = 770; continue '__sm; }
                __pc = 800; continue '__sm;
            }
            800 => {
                __rt.println(&[qb_str(&("AT 800"))]);
                { __pc = 840; continue '__sm; }
                __pc = 810; continue '__sm;
            }
            810 => {
                __rt.println(&[qb_str(&("AT 810"))]);
                { __pc = 790; continue '__sm; }
                __pc = 820; continue '__sm;
            }
            820 => {
                __rt.println(&[qb_str(&("AT 820"))]);
                { __pc = 860; continue '__sm; }
                __pc = 830; continue '__sm;
            }
            830 => {
                __rt.println(&[qb_str(&("AT 830"))]);
                { __pc = 810; continue '__sm; }
                __pc = 840; continue '__sm;
            }
            840 => {
                __rt.println(&[qb_str(&("AT 840"))]);
                { __pc = 880; continue '__sm; }
                __pc = 850; continue '__sm;
            }
            850 => {
                __rt.println(&[qb_str(&("AT 850"))]);
                { __pc = 830; continue '__sm; }
                __pc = 860; continue '__sm;
            }
            860 => {
                __rt.println(&[qb_str(&("AT 860"))]);
                { __pc = 900; continue '__sm; }
                __pc = 870; continue '__sm;
            }
            870 => {
                __rt.println(&[qb_str(&("AT 870"))]);
                { __pc = 850; continue '__sm; }
                __pc = 880; continue '__sm;
            }
            880 => {
                __rt.println(&[qb_str(&("AT 880"))]);
                { __pc = 920; continue '__sm; }
                __pc = 890; continue '__sm;
            }
            890 => {
                __rt.println(&[qb_str(&("AT 890"))]);
                { __pc = 870; continue '__sm; }
                __pc = 900; continue '__sm;
            }
            900 => {
                __rt.println(&[qb_str(&("AT 900"))]);
                { __pc = 940; continue '__sm; }
                __pc = 910; continue '__sm;
            }
            910 => {
                __rt.println(&[qb_str(&("AT 910"))]);
                { __pc = 890; continue '__sm; }
                __pc = 920; continue '__sm;
            }
            920 => {
                __rt.println(&[qb_str(&("AT 920"))]);
                { __pc = 960; continue '__sm; }
                __pc = 930; continue '__sm;
            }
            930 => {
                __rt.println(&[qb_str(&("AT 930"))]);
                { __pc = 910; continue '__sm; }
                __pc = 940; continue '__sm;
            }
            940 => {
                __rt.println(&[qb_str(&("AT 940"))]);
                { __pc = 980; continue '__sm; }
                __pc = 950; continue '__sm;
            }
            950 => {
                __rt.println(&[qb_str(&("AT 950"))]);
                { __pc = 930; continue '__sm; }
                __pc = 960; continue '__sm;
            }
            960 => {
                __rt.println(&[qb_str(&("AT 960"))]);
                { __pc = 1000; continue '__sm; }
                __pc = 970; continue '__sm;
            }
            970 => {
                __rt.println(&[qb_str(&("AT 970"))]);
                { __pc = 950; continue '__sm; }
                __pc = 980; continue '__sm;
            }
            980 => {
                __rt.println(&[qb_str(&("AT 980"))]);
                { __pc = 1000; continue '__sm; }
                __pc = 990; continue '__sm;
            }
            990 => {
                __rt.println(&[qb_str(&("AT 990"))]);
                { __pc = 970; continue '__sm; }
                __pc = 1000; continue '__sm;
            }
            1000 => {
                __rt.println(&[qb_str(&("AT 1000"))]);
                __rt.quit();
                break '__sm;
            }
            _ => break,
        }
    }
}
