// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

const maxdig: f64 = 1000.0f64;
const base: f64 = 10000.0f64;

#[derive(Default)]
struct GameState {
}

fn arctan(__rt: &mut Runtime, __gs: &mut GameState, x: &mut f64, cells: &mut f64, arr: &mut Vec<f64>) {
    let mut i: f64 = 0.0;
    let mut r: f64 = 0.0;
    let mut val: f64 = 0.0;
    let mut denom: f64 = 0.0;
    let mut sign: f64 = 0.0;
    let mut x2: f64 = 0.0;
    let mut allzero: f64 = 0.0;

    let mut num: Vec<f64> = vec![Default::default(); (maxdig+1.0) as usize];
    let mut term: Vec<f64> = vec![Default::default(); (maxdig+1.0) as usize];
    let mut tmp: Vec<f64> = vec![Default::default(); (maxdig+1.0) as usize];
    let mut i: f64 = Default::default();
    i = 0.0f64;
    let __for_to_i: f64 = (*cells);
    let __for_step_i: f64 = 1.0;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        arr[(i) as usize] = 0.0f64;
        i += __for_step_i;
    }
    i = 0.0f64;
    let __for_to_i: f64 = (*cells);
    let __for_step_i: f64 = 1.0;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        num[(i) as usize] = 0.0f64;
        i += __for_step_i;
    }
    num[(0.0f64) as usize] = qb_idiv(base, (*x));
    r = qb_mod(base, (*x));
    i = 1.0f64;
    let __for_to_i: f64 = (*cells);
    let __for_step_i: f64 = 1.0;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        val = (r * base);
        num[(i) as usize] = qb_idiv(val, (*x));
        r = qb_mod(val, (*x));
        i += __for_step_i;
    }
    i = 0.0f64;
    let __for_to_i: f64 = (*cells);
    let __for_step_i: f64 = 1.0;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        term[(i) as usize] = num[(i) as usize];
        i += __for_step_i;
    }
    addarr(__rt, __gs, cells, &mut *arr, &mut term);
    denom = 1.0f64;
    sign = (-1.0f64);
    x2 = ((*x) * (*x));
    loop {
        scalediv(__rt, __gs, &mut x2, cells, &mut term);
        denom = (denom + 2.0f64);
        i = 0.0f64;
        let __for_to_i: f64 = (*cells);
        let __for_step_i: f64 = 1.0;
        while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
            tmp[(i) as usize] = term[(i) as usize];
            i += __for_step_i;
        }
        scalediv(__rt, __gs, &mut denom, cells, &mut tmp);
        allzero = (-1.0f64);
        i = 0.0f64;
        let __for_to_i: f64 = (*cells);
        let __for_step_i: f64 = 1.0;
        while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
            if tmp[(i) as usize] != 0.0f64 {
                allzero = 0.0f64;
                break; // EXIT FOR
            }
            i += __for_step_i;
        }
        if qb_bool(allzero) {
            break; // EXIT DO
        }
        if sign == (-1.0f64) {
            let mut __arr_alias_0 = arr.clone();
            subarr(__rt, __gs, cells, &mut __arr_alias_0, &mut tmp, &mut *arr);
        } else {
            addarr(__rt, __gs, cells, &mut *arr, &mut tmp);
        }
        sign = (-sign);
    }
}

fn subarr(__rt: &mut Runtime, __gs: &mut GameState, cells: &mut f64, a: &mut Vec<f64>, b: &mut Vec<f64>, out: &mut Vec<f64>) {
    let mut i: f64 = 0.0;

    let mut i: f64 = Default::default();
    let mut tmp: Vec<f64> = vec![Default::default(); (maxdig+1.0) as usize];
    i = 0.0f64;
    let __for_to_i: f64 = (*cells);
    let __for_step_i: f64 = 1.0;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        tmp[(i) as usize] = (a[(i) as usize] - b[(i) as usize]);
        i += __for_step_i;
    }
    i = (*cells);
    let __for_to_i: f64 = 1.0f64;
    let __for_step_i: f64 = (-1.0f64);
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        if tmp[(i) as usize] < 0.0f64 {
            tmp[(i) as usize] = (tmp[(i) as usize] + base);
            tmp[((i - 1.0f64)) as usize] = (tmp[((i - 1.0f64)) as usize] - 1.0f64);
        }
        i += __for_step_i;
    }
    i = 0.0f64;
    let __for_to_i: f64 = (*cells);
    let __for_step_i: f64 = 1.0;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        out[(i) as usize] = tmp[(i) as usize];
        i += __for_step_i;
    }
}

fn addarr(__rt: &mut Runtime, __gs: &mut GameState, cells: &mut f64, arr: &mut Vec<f64>, b: &mut Vec<f64>) {
    let mut i: f64 = 0.0;

    let mut i: f64 = Default::default();
    i = 0.0f64;
    let __for_to_i: f64 = (*cells);
    let __for_step_i: f64 = 1.0;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        arr[(i) as usize] = (arr[(i) as usize] + b[(i) as usize]);
        i += __for_step_i;
    }
    i = (*cells);
    let __for_to_i: f64 = 1.0f64;
    let __for_step_i: f64 = (-1.0f64);
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        if arr[(i) as usize] >= base {
            arr[((i - 1.0f64)) as usize] = (arr[((i - 1.0f64)) as usize] + qb_idiv(arr[(i) as usize], base));
            arr[(i) as usize] = qb_mod(arr[(i) as usize], base);
        }
        i += __for_step_i;
    }
}

fn scalemul(__rt: &mut Runtime, __gs: &mut GameState, n: &mut f64, cells: &mut f64, arr: &mut Vec<f64>) {
    let mut i: f64 = 0.0;

    let mut i: f64 = Default::default();
    i = 0.0f64;
    let __for_to_i: f64 = (*cells);
    let __for_step_i: f64 = 1.0;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        arr[(i) as usize] = (arr[(i) as usize] * (*n));
        i += __for_step_i;
    }
    i = (*cells);
    let __for_to_i: f64 = 1.0f64;
    let __for_step_i: f64 = (-1.0f64);
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        if arr[(i) as usize] >= base {
            arr[((i - 1.0f64)) as usize] = (arr[((i - 1.0f64)) as usize] + qb_idiv(arr[(i) as usize], base));
            arr[(i) as usize] = qb_mod(arr[(i) as usize], base);
        }
        i += __for_step_i;
    }
}

fn scalediv(__rt: &mut Runtime, __gs: &mut GameState, n: &mut f64, cells: &mut f64, arr: &mut Vec<f64>) {
    let mut i: f64 = 0.0;
    let mut r: f64 = 0.0;
    let mut val: f64 = 0.0;

    let mut i: f64 = Default::default();
    r = 0.0f64;
    i = 0.0f64;
    let __for_to_i: f64 = (*cells);
    let __for_step_i: f64 = 1.0;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        val = (arr[(i) as usize] + (r * base));
        arr[(i) as usize] = qb_idiv(val, (*n));
        r = qb_mod(val, (*n));
        i += __for_step_i;
    }
}

fn printpi(__rt: &mut Runtime, __gs: &mut GameState, ndig: &mut f64, cells: &mut f64, arr: &mut Vec<f64>) {
    let mut i: f64 = 0.0;
    let mut digitsleft: f64 = 0.0;
    let mut chunk_s: String = String::new();

    let mut i: f64 = Default::default();
    __rt.print(&[qb_str(&("pi = ")), qb_str(&(qb_ltrim(&(qb_str_fn(qb_idiv(arr[(0.0f64) as usize], base)))))), qb_str(&("."))]);
    digitsleft = (*ndig);
    chunk_s = (qb_right(&(format!("{}{}" ,"0000",qb_ltrim(&(qb_str_fn(qb_mod(arr[(0.0f64) as usize], base)))))), 4.0f64)).to_string();
    if digitsleft >= 4.0f64 {
        __rt.print(&[qb_str(&(chunk_s))]);
        digitsleft = (digitsleft - 4.0f64);
    } else {
        __rt.print(&[qb_str(&(qb_left(&(chunk_s), digitsleft)))]);
        digitsleft = 0.0f64;
    }
    i = 1.0f64;
    while qb_bool(qb_and(qb_from_bool(digitsleft > 0.0f64), qb_from_bool(i <= (*cells)))) {
        chunk_s = (qb_right(&(format!("{}{}" ,"0000",qb_ltrim(&(qb_str_fn(arr[(i) as usize]))))), 4.0f64)).to_string();
        if digitsleft >= 4.0f64 {
            __rt.print(&[qb_str(&(chunk_s))]);
            digitsleft = (digitsleft - 4.0f64);
        } else {
            __rt.print(&[qb_str(&(qb_left(&(chunk_s), digitsleft)))]);
            digitsleft = 0.0f64;
        }
        i = (i + 1.0f64);
    }
    __rt.println(&[]);
}

fn main() {
    let mut __rt = Runtime::new();
    __rt.set_fullspeed(true);
    let mut __gs = GameState::default();

    let mut ans_s: String = String::new();
    let mut ndig: f64 = 0.0;
    let mut cells: f64 = 0.0;

    let mut a: Vec<f64> = vec![Default::default(); (maxdig+1.0) as usize];
    let mut b: Vec<f64> = vec![Default::default(); (maxdig+1.0) as usize];
    let mut c: Vec<f64> = vec![Default::default(); (maxdig+1.0) as usize];
    let t: Vec<f64> = vec![Default::default(); (maxdig+1.0) as usize];
    __rt.cls(0u8);
    __rt.println(&[qb_str(&("================================="))]);
    __rt.println(&[qb_str(&("   QBasic Pi Calculator"))]);
    __rt.println(&[qb_str(&("   Machin Formula Edition"))]);
    __rt.println(&[qb_str(&("================================="))]);
    __rt.println(&[]);
    __rt.print_str("Digits of pi to calculate (default=20): ? ");
    ans_s = __rt.input_line();
    if (ans_s).as_str() == "" {
        ndig = 20.0f64;
    } else {
        ndig = qb_val(&(ans_s));
    }
    if ndig < 1.0f64 {
        ndig = 1.0f64;
    }
    if ndig > 900.0f64 {
        __rt.println(&[qb_str(&("Capping at 900 digits."))]);
        ndig = 900.0f64;
    }
    __rt.println(&[]);
    __rt.println(&[qb_str(&("Computing pi to")), qb_print_num(ndig), qb_str(&("decimal places..."))]);
    __rt.println(&[]);
    cells = qb_int(((ndig / 4.0f64) + 4.0f64));
    let mut __tmp_num1: f64 = 5.0f64;
    arctan(&mut __rt, &mut __gs, &mut __tmp_num1, &mut cells, &mut a);
    let mut __tmp_num2: f64 = 4.0f64;
    scalemul(&mut __rt, &mut __gs, &mut __tmp_num2, &mut cells, &mut a);
    let mut __tmp_num3: f64 = 239.0f64;
    arctan(&mut __rt, &mut __gs, &mut __tmp_num3, &mut cells, &mut b);
    subarr(&mut __rt, &mut __gs, &mut cells, &mut a, &mut b, &mut c);
    let mut __tmp_num4: f64 = 4.0f64;
    scalemul(&mut __rt, &mut __gs, &mut __tmp_num4, &mut cells, &mut c);
    printpi(&mut __rt, &mut __gs, &mut ndig, &mut cells, &mut c);
    __rt.println(&[]);
    __rt.println(&[qb_str(&("Done!"))]);
    __rt.quit();
}
