// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

fn main() {
    let mut __rt = Runtime::new();
    let mut x: f64 = 0.0;
    let mut y: f64 = 0.0;
    let mut c: f64 = 0.0;

    let mut __pc: u32 = 10;
    '__sm: loop {
        match __pc {
            10 => {
                __rt.screen(1.0f64);
                __pc = 20; continue '__sm;
            }
            20 => {
                __rt.cls(0u8);
                __pc = 30; continue '__sm;
            }
            30 => {
                __rt.randomize(qb_timer());
                __pc = 40; continue '__sm;
            }
            40 => {
                let __tmp0 = __rt.rnd();
                x = qb_int((__tmp0 * 320.0f64));
                __pc = 50; continue '__sm;
            }
            50 => {
                let __tmp1 = __rt.rnd();
                y = qb_int((__tmp1 * 200.0f64));
                __pc = 60; continue '__sm;
            }
            60 => {
                let __tmp2 = __rt.rnd();
                c = qb_int((__tmp2 * 4.0f64));
                __pc = 70; continue '__sm;
            }
            70 => {
                __rt.pset(x, y, c);
                __pc = 80; continue '__sm;
            }
            80 => {
                { __pc = 40; continue '__sm; }
                break '__sm;
            }
            _ => break,
        }
    }
}
