// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

fn main() {
    let mut __rt = Runtime::new();
    __rt.set_fps(30.0);
    __rt.apply_behavioral_env();
    let mut x: f64 = 0.0;
    let mut y: f64 = 0.0;
    let mut c: f64 = 0.0;

    __rt.cls(0u8);
    __rt.screen(13.0f64);
    __rt.randomize(qb_timer());
    while (__rt.inkey()).as_str() == "" {
        let __tmp0 = __rt.rnd();
        x = qb_int((__tmp0 * 320.0f64));
        let __tmp1 = __rt.rnd();
        y = qb_int((__tmp1 * 200.0f64));
        let __tmp2 = __rt.rnd();
        c = qb_int((__tmp2 * 256.0f64));
        __rt.pset(x, y, c);
    }
    __rt.screen(0.0f64);
    __rt.cls(0u8);
    __rt.println(&[qb_str(&("Done."))]);
}
