// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

static __DATA: &[&str] = &["Insertion", "Bubble", "Heap", "Exchange", "Shell", "Quick", "Toggle Sound", "", "< ( Slower )", "> ( Faster )"];
static __DATA_PTR: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

const qb_false: f64 = 0_f64;
const qb_true: f64 = -1_f64;
const leftcolumn: f64 = 49_f64;
const numoptions: f64 = 11_f64;
const numsorts: f64 = 6_f64;

#[derive(Default)]
struct GameState {
    background: f64,
    foreground: f64,
    initrow: f64,
    maxcolors: f64,
    maxrow: f64,
    nosound: f64,
    optiontitle_s: Vec<String>,
    pause: f64,
    selection: f64,
    sortarray__length: Vec<f64>,
    sortarray__colorval: Vec<f64>,
    sortarray__barstring: Vec<String>,
    sortbackup__length: Vec<f64>,
    sortbackup__colorval: Vec<f64>,
    sortbackup__barstring: Vec<String>,
    starttime: f64,
}

fn boxinit(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut i: f64 = 0.0_f64;

    let mut __tmp_num0: f64 = 1_f64;
    let mut __tmp_num1: f64 = 22_f64;
    let mut __tmp_num2: f64 = (leftcolumn - 3_f64);
    let mut __tmp_num3: f64 = 78_f64;
    drawframe(__rt, __gs, &mut __tmp_num0, &mut __tmp_num1, &mut __tmp_num2, &mut __tmp_num3);
    __rt.locate(Some(3_f64), Some((leftcolumn + 2_f64)), None);
    __rt.print(&[qb_str(&("QBasic Sorting Demo"))]);
    __rt.locate(Some(5_f64), None, None);
    i = 1_f64;
    let __for_to_i: f64 = (numoptions - 1_f64);
    let __for_step_i: f64 = 1.0_f64;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        __rt.locate(None, Some(leftcolumn), None);
        __rt.println(&[qb_str(&(__gs.optiontitle_s[(i) as usize]))]);
        i += __for_step_i;
    }
    if qb_bool(qb_from_bool(__gs.pause > 1_f64)) {
        __rt.locate(None, Some(leftcolumn), None);
        __rt.print(&[qb_str(&(__gs.optiontitle_s[(numoptions) as usize]))]);
    }
    __gs.nosound = qb_not(__gs.nosound);
    let mut __tmp_num4: f64 = 12_f64;
    let mut __tmp_num5: f64 = (leftcolumn + 12_f64);
    togglesound(__rt, __gs, &mut __tmp_num4, &mut __tmp_num5);
    __rt.locate(Some((numoptions + 6_f64)), Some(leftcolumn), None);
    __rt.println(&[qb_str(&("Type first character of"))]);
    __rt.locate(None, Some(leftcolumn), None);
    __rt.println(&[qb_str(&("choice ( I B H E S Q T < > )"))]);
    __rt.locate(None, Some(leftcolumn), None);
    __rt.print(&[qb_str(&("or ESC key to end program: "))]);
}

fn bubblesort(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut limit: f64 = 0.0_f64;
    let mut switch: f64 = 0.0_f64;
    let mut row: f64 = 0.0_f64;

    limit = __gs.maxrow;
    loop {
        switch = qb_false;
        row = 1_f64;
        let __for_to_row: f64 = (limit - 1_f64);
        let __for_step_row: f64 = 1.0_f64;
        while (__for_step_row > 0.0 && row <= __for_to_row) || (__for_step_row < 0.0 && row >= __for_to_row) {
            if qb_bool(qb_from_bool(__gs.sortarray__length[(row) as usize] > __gs.sortarray__length[((row + 1_f64)) as usize])) {
                __gs.sortarray__length.swap((row) as usize, ((row + 1_f64)) as usize);
                __gs.sortarray__colorval.swap((row) as usize, ((row + 1_f64)) as usize);
                __gs.sortarray__barstring.swap((row) as usize, ((row + 1_f64)) as usize);
                let mut __tmp_num6: f64 = (row + 1_f64);
                swapbars(__rt, __gs, &mut row, &mut __tmp_num6);
                switch = row;
            }
            row += __for_step_row;
        }
        limit = switch;
        if !qb_bool(switch) { break; }
    }
}

fn checkscreen(__rt: &mut Runtime, __gs: &mut GameState) {
    __gs.initrow = 50_f64;
    __rt.locate(Some(__gs.initrow), Some(1_f64), None);
    __rt.locate(Some(1_f64), Some(1_f64), None);
    __rt.println(&[qb_str(&("x"))]);
    if qb_bool(qb_from_bool(qb_peek(0_f64) != qb_asc("x"))) {
        __gs.maxcolors = 15_f64;
    } else {
        __rt.locate(Some(1_f64), Some(1_f64), None);
        __rt.println(&[qb_str(&("y"))]);
        if qb_bool(qb_from_bool(qb_peek(0_f64) != qb_asc("y"))) {
            __gs.maxcolors = 15_f64;
        } else {
            __gs.maxcolors = 2_f64;
        }
    }
    __gs.maxrow = 43_f64;
}

fn drawframe(__rt: &mut Runtime, __gs: &mut GameState, topside: &mut f64, bottomside: &mut f64, leftside: &mut f64, rightside: &mut f64) {
    let mut framewidth: f64 = 0.0_f64;
    let mut row: f64 = 0.0_f64;

    let uleft: f64 = 201_f64;
    let uright: f64 = 187_f64;
    let lleft: f64 = 200_f64;
    let lright: f64 = 188_f64;
    let vertical: f64 = 186_f64;
    let horizontal: f64 = 205_f64;
    framewidth = (((*rightside) - (*leftside)) - 1_f64);
    __rt.locate(Some((*topside)), Some((*leftside)), None);
    __rt.print(&[qb_str(&(qb_chr(uleft))), qb_str(&(qb_string(framewidth, horizontal))), qb_str(&(qb_chr(uright)))]);
    row = ((*topside) + 1_f64);
    let __for_to_row: f64 = ((*bottomside) - 1_f64);
    let __for_step_row: f64 = 1.0_f64;
    while (__for_step_row > 0.0 && row <= __for_to_row) || (__for_step_row < 0.0 && row >= __for_to_row) {
        __rt.locate(Some(row), Some((*leftside)), None);
        __rt.print(&[qb_str(&(qb_chr(vertical))), qb_space(framewidth), qb_str(&(qb_chr(vertical)))]);
        row += __for_step_row;
    }
    __rt.locate(Some((*bottomside)), Some((*leftside)), None);
    __rt.print(&[qb_str(&(qb_chr(lleft))), qb_str(&(qb_string(framewidth, horizontal))), qb_str(&(qb_chr(lright)))]);
}

fn elapsedtime(__rt: &mut Runtime, __gs: &mut GameState, currentrow: &mut f64) {
    let qb_format: &str = "  &###.### seconds  ";
    __rt.color(__gs.foreground, Some(__gs.background));
    __rt.locate(Some((__gs.selection + 4_f64)), Some((leftcolumn - 2_f64)), None);
    let __pu_s7 = (__gs.optiontitle_s[(__gs.selection) as usize]).to_string();
    let __pu8 = qb_print_using(&(qb_format), &[QbVal::Str(&__pu_s7), QbVal::Num((qb_timer() - __gs.starttime))]);
    __rt.print(&[__pu8]);
    if qb_bool(__gs.nosound) {
        let __sf9: f64 = 30000_f64;
        let __sd9: f64 = __gs.pause;
        __rt.sound(__sf9, __sd9);
    } else {
        let __sf10: f64 = (60_f64 * (*currentrow));
        let __sd10: f64 = __gs.pause;
        __rt.sound(__sf10, __sd10);
    }
    __rt.color(__gs.maxcolors, Some(0_f64));
}

fn exchangesort(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut row: f64 = 0.0_f64;
    let mut smallestrow: f64 = 0.0_f64;
    let mut j: f64 = 0.0_f64;

    row = 1_f64;
    let __for_to_row: f64 = __gs.maxrow;
    let __for_step_row: f64 = 1.0_f64;
    while (__for_step_row > 0.0 && row <= __for_to_row) || (__for_step_row < 0.0 && row >= __for_to_row) {
        smallestrow = row;
        j = (row + 1_f64);
        let __for_to_j: f64 = __gs.maxrow;
        let __for_step_j: f64 = 1.0_f64;
        while (__for_step_j > 0.0 && j <= __for_to_j) || (__for_step_j < 0.0 && j >= __for_to_j) {
            if qb_bool(qb_from_bool(__gs.sortarray__length[(j) as usize] < __gs.sortarray__length[(smallestrow) as usize])) {
                smallestrow = j;
                elapsedtime(__rt, __gs, &mut j);
            }
            j += __for_step_j;
        }
        if qb_bool(qb_from_bool(smallestrow > row)) {
            __gs.sortarray__length.swap((row) as usize, (smallestrow) as usize);
            __gs.sortarray__colorval.swap((row) as usize, (smallestrow) as usize);
            __gs.sortarray__barstring.swap((row) as usize, (smallestrow) as usize);
            swapbars(__rt, __gs, &mut row, &mut smallestrow);
        }
        row += __for_step_row;
    }
}

fn heapsort(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut i: f64 = 0.0_f64;

    i = 2_f64;
    let __for_to_i: f64 = __gs.maxrow;
    let __for_step_i: f64 = 1.0_f64;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        percolateup(__rt, __gs, &mut i);
        i += __for_step_i;
    }
    i = __gs.maxrow;
    let __for_to_i: f64 = 2_f64;
    let __for_step_i: f64 = (-1_f64);
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        __gs.sortarray__length.swap((1_f64) as usize, (i) as usize);
        __gs.sortarray__colorval.swap((1_f64) as usize, (i) as usize);
        __gs.sortarray__barstring.swap((1_f64) as usize, (i) as usize);
        let mut __tmp_num11: f64 = 1_f64;
        swapbars(__rt, __gs, &mut __tmp_num11, &mut i);
        let mut __tmp_num12: f64 = (i - 1_f64);
        percolatedown(__rt, __gs, &mut __tmp_num12);
        i += __for_step_i;
    }
}

fn initialize(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut i: f64 = 0.0_f64;
    let mut maxindex: f64 = 0.0_f64;
    let mut index: f64 = 0.0_f64;
    let mut barlength: f64 = 0.0_f64;

    let mut temparray: Vec<f64> = vec![Default::default(); (43_f64+1.0) as usize];
    checkscreen(__rt, __gs);
    i = 1_f64;
    let __for_to_i: f64 = __gs.maxrow;
    let __for_step_i: f64 = 1.0_f64;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        temparray[(i) as usize] = i;
        i += __for_step_i;
    }
    maxindex = __gs.maxrow;
    __rt.randomize(qb_timer());
    i = 1_f64;
    let __for_to_i: f64 = __gs.maxrow;
    let __for_step_i: f64 = 1.0_f64;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        let __tmp13 = randint(__rt, __gs, 1_f64, maxindex);
        index = __tmp13;
        barlength = temparray[(index) as usize];
        temparray[(index) as usize] = temparray[(maxindex) as usize];
        maxindex = (maxindex - 1_f64);
        __gs.sortbackup__length[(i) as usize] = barlength;
        __gs.sortbackup__barstring[(i) as usize] = (qb_string(barlength, 223_f64)).to_string();
        if qb_bool(qb_from_bool(__gs.maxcolors > 2_f64)) {
            __gs.sortbackup__colorval[(i) as usize] = (qb_mod(barlength, __gs.maxcolors) + 1_f64);
        } else {
            __gs.sortbackup__colorval[(i) as usize] = __gs.maxcolors;
        }
        i += __for_step_i;
    }
    i = 1_f64;
    let __for_to_i: f64 = numoptions;
    let __for_step_i: f64 = 1.0_f64;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        __gs.optiontitle_s[(i) as usize] = qb_read_data(&__DATA, &__DATA_PTR).parse().unwrap_or_default();
        i += __for_step_i;
    }
    __rt.cls(0u8);
    reinitialize(__rt, __gs);
    __gs.nosound = qb_false;
    __gs.pause = 2_f64;
    boxinit(__rt, __gs);
}

fn insertionsort(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut tempval: f64 = 0.0_f64;
    let mut row: f64 = 0.0_f64;
    let mut templength: f64 = 0.0_f64;
    let mut j: f64 = 0.0_f64;

    let mut tempval__length: f64 = Default::default();
    let mut tempval__colorval: f64 = Default::default();
    let mut tempval__barstring: String = Default::default();
    row = 2_f64;
    let __for_to_row: f64 = __gs.maxrow;
    let __for_step_row: f64 = 1.0_f64;
    while (__for_step_row > 0.0 && row <= __for_to_row) || (__for_step_row < 0.0 && row >= __for_to_row) {
        tempval__length = __gs.sortarray__length[(row) as usize].clone();
        tempval__colorval = __gs.sortarray__colorval[(row) as usize].clone();
        tempval__barstring = __gs.sortarray__barstring[(row) as usize].clone();
        templength = tempval__length;
        j = row;
        let __for_to_j: f64 = 2_f64;
        let __for_step_j: f64 = (-1_f64);
        while (__for_step_j > 0.0 && j <= __for_to_j) || (__for_step_j < 0.0 && j >= __for_to_j) {
            if qb_bool(qb_from_bool(__gs.sortarray__length[((j - 1_f64)) as usize] > templength)) {
                __gs.sortarray__length[(j) as usize] = __gs.sortarray__length[((j - 1_f64)) as usize].clone();
                __gs.sortarray__colorval[(j) as usize] = __gs.sortarray__colorval[((j - 1_f64)) as usize].clone();
                __gs.sortarray__barstring[(j) as usize] = __gs.sortarray__barstring[((j - 1_f64)) as usize].clone();
                printonebar(__rt, __gs, &mut j);
                elapsedtime(__rt, __gs, &mut j);
            } else {
                break; // EXIT FOR
            }
            j += __for_step_j;
        }
        __gs.sortarray__length[(j) as usize] = tempval__length.clone();
        __gs.sortarray__colorval[(j) as usize] = tempval__colorval.clone();
        __gs.sortarray__barstring[(j) as usize] = tempval__barstring.clone();
        printonebar(__rt, __gs, &mut j);
        elapsedtime(__rt, __gs, &mut j);
        row += __for_step_row;
    }
}

fn percolatedown(__rt: &mut Runtime, __gs: &mut GameState, maxlevel: &mut f64) {
    let mut i: f64 = 0.0_f64;
    let mut child: f64 = 0.0_f64;

    i = 1_f64;
    loop {
        child = (2_f64 * i);
        if qb_bool(qb_from_bool(child > (*maxlevel))) {
            break; // EXIT DO
        }
        if qb_bool(qb_from_bool((child + 1_f64) <= (*maxlevel))) {
            if qb_bool(qb_from_bool(__gs.sortarray__length[((child + 1_f64)) as usize] > __gs.sortarray__length[(child) as usize])) {
                child = (child + 1_f64);
            }
        }
        if qb_bool(qb_from_bool(__gs.sortarray__length[(i) as usize] < __gs.sortarray__length[(child) as usize])) {
            __gs.sortarray__length.swap((i) as usize, (child) as usize);
            __gs.sortarray__colorval.swap((i) as usize, (child) as usize);
            __gs.sortarray__barstring.swap((i) as usize, (child) as usize);
            swapbars(__rt, __gs, &mut i, &mut child);
            i = child;
        } else {
            break; // EXIT DO
        }
    }
}

fn percolateup(__rt: &mut Runtime, __gs: &mut GameState, maxlevel: &mut f64) {
    let mut i: f64 = 0.0_f64;
    let mut parent: f64 = 0.0_f64;

    i = (*maxlevel);
    while !qb_bool(qb_from_bool(i == 1_f64)) {
        parent = qb_idiv(i, 2_f64);
        if qb_bool(qb_from_bool(__gs.sortarray__length[(i) as usize] > __gs.sortarray__length[(parent) as usize])) {
            __gs.sortarray__length.swap((parent) as usize, (i) as usize);
            __gs.sortarray__colorval.swap((parent) as usize, (i) as usize);
            __gs.sortarray__barstring.swap((parent) as usize, (i) as usize);
            swapbars(__rt, __gs, &mut parent, &mut i);
            i = parent;
        } else {
            break; // EXIT DO
        }
    }
}

fn printonebar(__rt: &mut Runtime, __gs: &mut GameState, row: &mut f64) {
    __rt.locate(Some((*row)), Some(1_f64), None);
    __rt.color(__gs.sortarray__colorval[((*row)) as usize], None);
    __rt.print(&[qb_str(&(__gs.sortarray__barstring[((*row)) as usize]))]);
}

fn quicksort(__rt: &mut Runtime, __gs: &mut GameState, low: &mut f64, high: &mut f64) {
    let mut randindex: f64 = 0.0_f64;
    let mut partition: f64 = 0.0_f64;
    let mut i: f64 = 0.0_f64;
    let mut j: f64 = 0.0_f64;

    if qb_bool(qb_from_bool((*low) < (*high))) {
        if qb_bool(qb_from_bool(((*high) - (*low)) == 1_f64)) {
            if qb_bool(qb_from_bool(__gs.sortarray__length[((*low)) as usize] > __gs.sortarray__length[((*high)) as usize])) {
                __gs.sortarray__length.swap(((*low)) as usize, ((*high)) as usize);
                __gs.sortarray__colorval.swap(((*low)) as usize, ((*high)) as usize);
                __gs.sortarray__barstring.swap(((*low)) as usize, ((*high)) as usize);
                swapbars(__rt, __gs, low, high);
            }
        } else {
            let __tmp14 = randint(__rt, __gs, (*low), (*high));
            randindex = __tmp14;
            __gs.sortarray__length.swap(((*high)) as usize, (randindex) as usize);
            __gs.sortarray__colorval.swap(((*high)) as usize, (randindex) as usize);
            __gs.sortarray__barstring.swap(((*high)) as usize, (randindex) as usize);
            swapbars(__rt, __gs, high, &mut randindex);
            partition = __gs.sortarray__length[((*high)) as usize];
            loop {
                i = (*low);
                j = (*high);
                while qb_bool(qb_and(qb_from_bool(i < j), qb_from_bool(__gs.sortarray__length[(i) as usize] <= partition))) {
                    i = (i + 1_f64);
                }
                while qb_bool(qb_and(qb_from_bool(j > i), qb_from_bool(__gs.sortarray__length[(j) as usize] >= partition))) {
                    j = (j - 1_f64);
                }
                if qb_bool(qb_from_bool(i < j)) {
                    __gs.sortarray__length.swap((i) as usize, (j) as usize);
                    __gs.sortarray__colorval.swap((i) as usize, (j) as usize);
                    __gs.sortarray__barstring.swap((i) as usize, (j) as usize);
                    swapbars(__rt, __gs, &mut i, &mut j);
                }
                if !qb_bool(qb_from_bool(i < j)) { break; }
            }
            __gs.sortarray__length.swap((i) as usize, ((*high)) as usize);
            __gs.sortarray__colorval.swap((i) as usize, ((*high)) as usize);
            __gs.sortarray__barstring.swap((i) as usize, ((*high)) as usize);
            swapbars(__rt, __gs, &mut i, high);
            if qb_bool(qb_from_bool((i - (*low)) < ((*high) - i))) {
                let mut __tmp_num15: f64 = (i - 1_f64);
                quicksort(__rt, __gs, low, &mut __tmp_num15);
                let mut __tmp_num16: f64 = (i + 1_f64);
                quicksort(__rt, __gs, &mut __tmp_num16, high);
            } else {
                let mut __tmp_num17: f64 = (i + 1_f64);
                quicksort(__rt, __gs, &mut __tmp_num17, high);
                let mut __tmp_num18: f64 = (i - 1_f64);
                quicksort(__rt, __gs, low, &mut __tmp_num18);
            }
        }
    }
}

fn reinitialize(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut i: f64 = 0.0_f64;

    i = 1_f64;
    let __for_to_i: f64 = __gs.maxrow;
    let __for_step_i: f64 = 1.0_f64;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        __gs.sortarray__length[(i) as usize] = __gs.sortbackup__length[(i) as usize].clone();
        __gs.sortarray__colorval[(i) as usize] = __gs.sortbackup__colorval[(i) as usize].clone();
        __gs.sortarray__barstring[(i) as usize] = __gs.sortbackup__barstring[(i) as usize].clone();
        i += __for_step_i;
    }
    i = 1_f64;
    let __for_to_i: f64 = __gs.maxrow;
    let __for_step_i: f64 = 1.0_f64;
    while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
        __rt.locate(Some(i), Some(1_f64), None);
        __rt.color(__gs.sortarray__colorval[(i) as usize], None);
        __rt.print(&[qb_str(&(__gs.sortarray__barstring[(i) as usize]))]);
        i += __for_step_i;
    }
    __rt.color(__gs.maxcolors, Some(0_f64));
}

fn shellsort(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut offset: f64 = 0.0_f64;
    let mut limit: f64 = 0.0_f64;
    let mut switch: f64 = 0.0_f64;
    let mut row: f64 = 0.0_f64;

    offset = qb_idiv(__gs.maxrow, 2_f64);
    while qb_bool(qb_from_bool(offset > 0_f64)) {
        limit = (__gs.maxrow - offset);
        loop {
            switch = qb_false;
            row = 1_f64;
            let __for_to_row: f64 = limit;
            let __for_step_row: f64 = 1.0_f64;
            while (__for_step_row > 0.0 && row <= __for_to_row) || (__for_step_row < 0.0 && row >= __for_to_row) {
                if qb_bool(qb_from_bool(__gs.sortarray__length[(row) as usize] > __gs.sortarray__length[((row + offset)) as usize])) {
                    __gs.sortarray__length.swap((row) as usize, ((row + offset)) as usize);
                    __gs.sortarray__colorval.swap((row) as usize, ((row + offset)) as usize);
                    __gs.sortarray__barstring.swap((row) as usize, ((row + offset)) as usize);
                    let mut __tmp_num19: f64 = (row + offset);
                    swapbars(__rt, __gs, &mut row, &mut __tmp_num19);
                    switch = row;
                }
                row += __for_step_row;
            }
            limit = (switch - offset);
            if !qb_bool(switch) { break; }
        }
        offset = qb_idiv(offset, 2_f64);
    }
}

fn sortmenu(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut escape_s: String = String::new();
    let mut option_s: String = String::new();
    let mut choice_s: String = String::new();

    escape_s = (qb_chr(27_f64)).to_string();
    option_s = (format!("{}{}" ,"IBHESQ><T",escape_s)).to_string();
    loop {
        __rt.locate(Some((numoptions + 8_f64)), Some((leftcolumn + 27_f64)), Some(1_f64));
        let __tmp20 = __rt.input_str(1_f64);
        choice_s = (qb_ucase(&(__tmp20))).to_string();
        __gs.selection = qb_instr(1.0, &(option_s), &(choice_s));
        if qb_bool(qb_and(qb_from_bool(__gs.selection >= 1_f64), qb_from_bool(__gs.selection <= numsorts))) {
            reinitialize(__rt, __gs);
            __rt.locate(None, None, Some(0_f64));
            __gs.foreground = 0_f64;
            __gs.background = 7_f64;
            __gs.starttime = qb_timer();
        }
        let __sel = choice_s.clone();
        if __sel == "I".to_string() {
            insertionsort(__rt, __gs);
        } else if __sel == "B".to_string() {
            bubblesort(__rt, __gs);
        } else if __sel == "H".to_string() {
            heapsort(__rt, __gs);
        } else if __sel == "E".to_string() {
            exchangesort(__rt, __gs);
        } else if __sel == "S".to_string() {
            shellsort(__rt, __gs);
        } else if __sel == "Q".to_string() {
            let mut __tmp_num21: f64 = 1_f64;
            let mut __tmp_gs22: f64 = __gs.maxrow;
            quicksort(__rt, __gs, &mut __tmp_num21, &mut __tmp_gs22);
            __gs.maxrow = __tmp_gs22;
        } else if __sel == ">".to_string() {
            __gs.pause = ((2_f64 * __gs.pause) / 3_f64);
            boxinit(__rt, __gs);
        } else if __sel == "<".to_string() {
            if qb_bool(qb_from_bool(((3_f64 * __gs.pause) / 2_f64) < 13000_f64)) {
                __gs.pause = ((3_f64 * __gs.pause) / 2_f64);
            }
            boxinit(__rt, __gs);
        } else if __sel == "T".to_string() {
            let mut __tmp_num23: f64 = 12_f64;
            let mut __tmp_num24: f64 = (leftcolumn + 12_f64);
            togglesound(__rt, __gs, &mut __tmp_num23, &mut __tmp_num24);
        } else if __sel == escape_s.to_string() {
            break; // EXIT DO
        } else {
        }
        if qb_bool(qb_and(qb_from_bool(__gs.selection >= 1_f64), qb_from_bool(__gs.selection <= numsorts))) {
            __gs.foreground = __gs.maxcolors;
            __gs.background = 0_f64;
            let mut __tmp_num25: f64 = 0_f64;
            elapsedtime(__rt, __gs, &mut __tmp_num25);
        }
    }
}

fn swapbars(__rt: &mut Runtime, __gs: &mut GameState, row1: &mut f64, row2: &mut f64) {
    printonebar(__rt, __gs, row1);
    printonebar(__rt, __gs, row2);
    elapsedtime(__rt, __gs, row1);
}

fn togglesound(__rt: &mut Runtime, __gs: &mut GameState, row: &mut f64, column: &mut f64) {
    __gs.nosound = qb_not(__gs.nosound);
    __rt.locate(Some((*row)), Some((*column)), None);
    if qb_bool(__gs.nosound) {
        __rt.print(&[qb_str(&(": OFF"))]);
    } else {
        __rt.print(&[qb_str(&(": ON "))]);
    }
}

fn randint(__rt: &mut Runtime, __gs: &mut GameState, mut lower: f64, mut upper: f64) -> f64 {
    let mut __fn_ret: f64 = Default::default();
    let __tmp26 = __rt.rnd();
    __fn_ret = (qb_int((__tmp26 * ((upper - lower) + 1_f64))) + lower);
    __fn_ret
}

fn main() {
    let mut __rt = Runtime::new();
    let mut __gs = GameState::default();

    __gs.sortarray__length = vec![0.0_f64; (43_f64+1.0) as usize];
    __gs.sortarray__colorval = vec![0.0_f64; (43_f64+1.0) as usize];
    __gs.sortarray__barstring = vec![String::new(); (43_f64+1.0) as usize];
    __gs.sortbackup__length = vec![0.0_f64; (43_f64+1.0) as usize];
    __gs.sortbackup__colorval = vec![0.0_f64; (43_f64+1.0) as usize];
    __gs.sortbackup__barstring = vec![String::new(); (43_f64+1.0) as usize];
    __gs.optiontitle_s = vec![Default::default(); (numoptions+1.0) as usize];
    initialize(&mut __rt, &mut __gs);
    sortmenu(&mut __rt, &mut __gs);
    __rt.color(7_f64, Some(0_f64));
    __rt.cls(0u8);
    __rt.quit();
    // label: GetRow
    if qb_bool(qb_from_bool(__gs.initrow == 50_f64)) {
        __gs.initrow = 43_f64;
        __rt.error_pending = false;
    } else {
        __gs.initrow = 25_f64;
        __rt.error_pending = false;
    }
    // label: RowTrap
    __gs.maxrow = 25_f64;
    __rt.error_pending = false;
}
