// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

const pi: f64 = 3.14159_f64;
const qb_true: f64 = -1_f64;
const qb_false: f64 = 0_f64;
const back: f64 = 0_f64;
const trow: f64 = 24_f64;
const tcol: f64 = 60_f64;
const rndm: f64 = -1_f64;
const start: f64 = 0_f64;
const qb_continue: f64 = 1_f64;
const vga: f64 = 12_f64;
const mcga: f64 = 13_f64;
const ega256: f64 = 9_f64;
const ega64: f64 = 8_f64;
const mono: f64 = 10_f64;
const herc: f64 = 3_f64;
const cga: f64 = 1_f64;

#[derive(Default)]
struct GameState {
    available: String,
    bestmode: f64,
    index: Vec<f64>,
    initrows: f64,
    max: f64,
    pal: Vec<f64>,
    t__x1: Vec<f64>,
    t__x2: Vec<f64>,
    t__x3: Vec<f64>,
    t__x4: Vec<f64>,
    t__y1: Vec<f64>,
    t__y2: Vec<f64>,
    t__y3: Vec<f64>,
    t__y4: Vec<f64>,
    t__z1: Vec<f64>,
    t__xc: Vec<f64>,
    t__yc: Vec<f64>,
    t__tcolor: Vec<f64>,
    tor__panel: f64,
    tor__sect: f64,
    tor__thick: f64,
    tor__xdegree: f64,
    tor__ydegree: f64,
    tor__bord: String,
    tor__delay: f64,
    vc__scrn: f64,
    vc__colors: f64,
    vc__atribs: f64,
    vc__xpix: f64,
    vc__ypix: f64,
    vc__tcol: f64,
    vc__trow: f64,
}

fn counttiles(__rt: &mut Runtime, __gs: &mut GameState, t1: &mut f64, t2: &mut f64) {
    __rt.locate(Some((trow - 1_f64)), Some(tcol), None);
    __rt.print(&[qb_str(&(qb_space(19_f64)))]);
    if qb_bool(qb_and(qb_from_bool((*t1) > 0_f64), qb_from_bool((*t2) > 0_f64))) {
        __rt.locate(Some((trow - 1_f64)), Some(tcol), None);
        __rt.print(&[qb_str(&("Tile "))]);
        let __pu0 = qb_print_using(&(" ###"), &[QbVal::Num((*t1))]);
        __rt.print(&[__pu0]);
        let __pu1 = qb_print_using(&(" ###"), &[QbVal::Num((*t2))]);
        __rt.print(&[__pu1]);
    }
}

fn delay(__rt: &mut Runtime, __gs: &mut GameState, seconds: &mut f64) {
    let mut begin: f64 = 0.0_f64;

    begin = qb_timer();
    while !qb_bool(qb_or(qb_from_bool((qb_timer() - begin) > (*seconds)), qb_from_bool((qb_timer() - begin) < 0_f64))) {
    }
}

fn getconfig(__rt: &mut Runtime, __gs: &mut GameState) {
    __gs.initrows = 50_f64;
    __rt.locate(Some(__gs.initrows), Some(1_f64), None);
    __gs.bestmode = vga;
    __gs.available = ("12789BCD").to_string();
    __rt.screen(__gs.bestmode);
    if __rt.error_pending { __rt.error_pending = false; }
    if qb_bool(qb_from_bool(__gs.bestmode == ega256)) {
        __rt.screen(8_f64);
        if __rt.error_pending { __rt.error_pending = false; }
    }
    __rt.screen(0_f64);
}

fn message(__rt: &mut Runtime, __gs: &mut GameState, text_s: &mut String) {
    __rt.locate(Some(trow), Some(tcol), None);
    __rt.print(&[qb_str(&(qb_space(19_f64)))]);
    __rt.locate(Some(trow), Some(tcol), None);
    __rt.color(7_f64, None);
    __rt.print(&[qb_str(&(text_s))]);
    __rt.color(23_f64, None);
    __rt.print(&[qb_str(&(" . . ."))]);
    __rt.color(7_f64, None);
}

fn setconfig(__rt: &mut Runtime, __gs: &mut GameState, mode: &mut f64) {
    let __sel = (*mode);
    if __sel == 1_f64 {
        if qb_bool(qb_or(qb_from_bool(__gs.bestmode == cga), qb_from_bool(__gs.bestmode == mcga))) {
            __gs.vc__colors = 0_f64;
        } else {
            __gs.vc__colors = 16_f64;
        }
        __gs.vc__atribs = 4_f64;
        __gs.vc__xpix = 319_f64;
        __gs.vc__ypix = 199_f64;
        __gs.vc__tcol = 40_f64;
        __gs.vc__trow = 25_f64;
    } else if __sel == 2_f64 {
        if qb_bool(qb_or(qb_from_bool(__gs.bestmode == cga), qb_from_bool(__gs.bestmode == mcga))) {
            __gs.vc__colors = 0_f64;
        } else {
            __gs.vc__colors = 16_f64;
        }
        __gs.vc__atribs = 2_f64;
        __gs.vc__xpix = 639_f64;
        __gs.vc__ypix = 199_f64;
        __gs.vc__tcol = 80_f64;
        __gs.vc__trow = 25_f64;
    } else if __sel == 3_f64 {
        __gs.vc__colors = 0_f64;
        __gs.vc__atribs = 2_f64;
        __gs.vc__xpix = 720_f64;
        __gs.vc__ypix = 348_f64;
        __gs.vc__tcol = 80_f64;
        __gs.vc__trow = 25_f64;
    } else if __sel == 7_f64 {
        __gs.vc__colors = 16_f64;
        __gs.vc__atribs = 16_f64;
        __gs.vc__xpix = 319_f64;
        __gs.vc__ypix = 199_f64;
        __gs.vc__tcol = 40_f64;
        __gs.vc__trow = 25_f64;
    } else if __sel == 8_f64 {
        __gs.vc__colors = 16_f64;
        __gs.vc__atribs = 16_f64;
        __gs.vc__xpix = 639_f64;
        __gs.vc__ypix = 199_f64;
        __gs.vc__tcol = 80_f64;
        __gs.vc__trow = 25_f64;
    } else if __sel == 9_f64 {
        __gs.vc__colors = 64_f64;
        if qb_bool(qb_from_bool(__gs.bestmode == ega64)) {
            __gs.vc__atribs = 4_f64;
        } else {
            __gs.vc__atribs = 16_f64;
        }
        __gs.vc__xpix = 639_f64;
        __gs.vc__ypix = 349_f64;
        __gs.vc__tcol = 80_f64;
        __gs.vc__trow = 25_f64;
    } else if __sel == 10_f64 {
        __gs.vc__colors = 0_f64;
        __gs.vc__atribs = 2_f64;
        __gs.vc__xpix = 319_f64;
        __gs.vc__ypix = 199_f64;
        __gs.vc__tcol = 80_f64;
        __gs.vc__trow = 25_f64;
    } else if __sel == 11_f64 {
        __gs.vc__colors = 216_f64;
        __gs.vc__atribs = 2_f64;
        __gs.vc__xpix = 639_f64;
        __gs.vc__ypix = 479_f64;
        __gs.vc__tcol = 80_f64;
        __gs.vc__trow = 30_f64;
    } else if __sel == 12_f64 {
        __gs.vc__colors = 216_f64;
        __gs.vc__atribs = 16_f64;
        __gs.vc__xpix = 639_f64;
        __gs.vc__ypix = 479_f64;
        __gs.vc__tcol = 80_f64;
        __gs.vc__trow = 30_f64;
    } else if __sel == 13_f64 {
        __gs.vc__colors = 216_f64;
        __gs.vc__atribs = 256_f64;
        __gs.vc__xpix = 639_f64;
        __gs.vc__ypix = 479_f64;
        __gs.vc__tcol = 40_f64;
        __gs.vc__trow = 25_f64;
    } else {
        __gs.vc__colors = 16_f64;
        __gs.vc__atribs = 16_f64;
        __gs.vc__xpix = 0_f64;
        __gs.vc__ypix = 0_f64;
        __gs.vc__tcol = 80_f64;
        __gs.vc__trow = 25_f64;
        __gs.vc__scrn = 0_f64;
        return; // EXIT SUB
    }
    __gs.vc__scrn = (*mode);
}

fn setpalette(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut index: f64 = 0.0_f64;
    let mut bs: f64 = 0.0_f64;
    let mut gs: f64 = 0.0_f64;
    let mut rs: f64 = 0.0_f64;
    let mut hs: f64 = 0.0_f64;
    let mut hrs: f64 = 0.0_f64;
    let mut hgs: f64 = 0.0_f64;
    let mut hbs: f64 = 0.0_f64;

    if qb_bool(__gs.vc__colors) {
        let __sel = __gs.vc__scrn;
        if __sel == 1_f64 || __sel == 2_f64 || __sel == 7_f64 || __sel == 8_f64 {
            index = 0_f64;
            bs = 0_f64;
            let __for_to_bs: f64 = 1_f64;
            let __for_step_bs: f64 = 1.0_f64;
            while (__for_step_bs > 0.0 && bs <= __for_to_bs) || (__for_step_bs < 0.0 && bs >= __for_to_bs) {
                gs = 0_f64;
                let __for_to_gs: f64 = 1_f64;
                let __for_step_gs: f64 = 1.0_f64;
                while (__for_step_gs > 0.0 && gs <= __for_to_gs) || (__for_step_gs < 0.0 && gs >= __for_to_gs) {
                    rs = 0_f64;
                    let __for_to_rs: f64 = 1_f64;
                    let __for_step_rs: f64 = 1.0_f64;
                    while (__for_step_rs > 0.0 && rs <= __for_to_rs) || (__for_step_rs < 0.0 && rs >= __for_to_rs) {
                        hs = 0_f64;
                        let __for_to_hs: f64 = 1_f64;
                        let __for_step_hs: f64 = 1.0_f64;
                        while (__for_step_hs > 0.0 && hs <= __for_to_hs) || (__for_step_hs < 0.0 && hs >= __for_to_hs) {
                            __gs.pal[(index) as usize] = ((((hs * 8_f64) + (rs * 4_f64)) + (gs * 2_f64)) + bs);
                            index = (index + 1_f64);
                            hs += __for_step_hs;
                        }
                        rs += __for_step_rs;
                    }
                    gs += __for_step_gs;
                }
                bs += __for_step_bs;
            }
        } else if __sel == 9_f64 {
            index = 0_f64;
            bs = 0_f64;
            let __for_to_bs: f64 = 1_f64;
            let __for_step_bs: f64 = 1.0_f64;
            while (__for_step_bs > 0.0 && bs <= __for_to_bs) || (__for_step_bs < 0.0 && bs >= __for_to_bs) {
                gs = 0_f64;
                let __for_to_gs: f64 = 1_f64;
                let __for_step_gs: f64 = 1.0_f64;
                while (__for_step_gs > 0.0 && gs <= __for_to_gs) || (__for_step_gs < 0.0 && gs >= __for_to_gs) {
                    rs = 0_f64;
                    let __for_to_rs: f64 = 1_f64;
                    let __for_step_rs: f64 = 1.0_f64;
                    while (__for_step_rs > 0.0 && rs <= __for_to_rs) || (__for_step_rs < 0.0 && rs >= __for_to_rs) {
                        hrs = 0_f64;
                        let __for_to_hrs: f64 = 1_f64;
                        let __for_step_hrs: f64 = 1.0_f64;
                        while (__for_step_hrs > 0.0 && hrs <= __for_to_hrs) || (__for_step_hrs < 0.0 && hrs >= __for_to_hrs) {
                            hgs = 0_f64;
                            let __for_to_hgs: f64 = 1_f64;
                            let __for_step_hgs: f64 = 1.0_f64;
                            while (__for_step_hgs > 0.0 && hgs <= __for_to_hgs) || (__for_step_hgs < 0.0 && hgs >= __for_to_hgs) {
                                hbs = 0_f64;
                                let __for_to_hbs: f64 = 1_f64;
                                let __for_step_hbs: f64 = 1.0_f64;
                                while (__for_step_hbs > 0.0 && hbs <= __for_to_hbs) || (__for_step_hbs < 0.0 && hbs >= __for_to_hbs) {
                                    __gs.pal[(index) as usize] = ((((((rs * 32_f64) + (gs * 16_f64)) + (bs * 8_f64)) + (hrs * 4_f64)) + (hgs * 2_f64)) + hbs);
                                    index = (index + 1_f64);
                                    hbs += __for_step_hbs;
                                }
                                hgs += __for_step_hgs;
                            }
                            hrs += __for_step_hrs;
                        }
                        rs += __for_step_rs;
                    }
                    gs += __for_step_gs;
                }
                bs += __for_step_bs;
            }
        } else if __sel == 11_f64 || __sel == 12_f64 || __sel == 13_f64 {
            index = 0_f64;
            rs = 0_f64;
            let __for_to_rs: f64 = 63_f64;
            let __for_step_rs: f64 = 11_f64;
            while (__for_step_rs > 0.0 && rs <= __for_to_rs) || (__for_step_rs < 0.0 && rs >= __for_to_rs) {
                bs = 0_f64;
                let __for_to_bs: f64 = 63_f64;
                let __for_step_bs: f64 = 11_f64;
                while (__for_step_bs > 0.0 && bs <= __for_to_bs) || (__for_step_bs < 0.0 && bs >= __for_to_bs) {
                    gs = 0_f64;
                    let __for_to_gs: f64 = 63_f64;
                    let __for_step_gs: f64 = 11_f64;
                    while (__for_step_gs > 0.0 && gs <= __for_to_gs) || (__for_step_gs < 0.0 && gs >= __for_to_gs) {
                        __gs.pal[(index) as usize] = (((65536_f64 * bs) + (256_f64 * gs)) + rs);
                        index = (index + 1_f64);
                        gs += __for_step_gs;
                    }
                    bs += __for_step_bs;
                }
                rs += __for_step_rs;
            }
        } else {
        }
        if qb_bool(qb_from_bool(__gs.vc__atribs > 2_f64)) {
            torusrotate(__rt, __gs, &mut rndm);
        }
    }
}

fn tiledraw(__rt: &mut Runtime, __gs: &mut GameState, t__x1: &mut f64, t__x2: &mut f64, t__x3: &mut f64, t__x4: &mut f64, t__y1: &mut f64, t__y2: &mut f64, t__y3: &mut f64, t__y4: &mut f64, t__z1: &mut f64, t__xc: &mut f64, t__yc: &mut f64, t__tcolor: &mut f64) {
    let mut border: f64 = 0.0_f64;

    border = (__gs.vc__atribs - 1_f64);
    if qb_bool(qb_from_bool(__gs.vc__atribs == 2_f64)) {
        __rt.line((*t__x1),(*t__y1),(*t__x2),(*t__y2),(*t__tcolor));
        __rt.line_to((*t__x3),(*t__y3),(*t__tcolor));
        __rt.line_to((*t__x4),(*t__y4),(*t__tcolor));
        __rt.line_to((*t__x1),(*t__y1),(*t__tcolor));
        return; // EXIT SUB
    } else {
        __rt.line((*t__x1),(*t__y1),(*t__x2),(*t__y2),border);
        __rt.line_to((*t__x3),(*t__y3),border);
        __rt.line_to((*t__x4),(*t__y4),border);
        __rt.line_to((*t__x1),(*t__y1),border);
    }
    if qb_bool(inside(__rt, __gs, &mut *t__x1, &mut *t__x2, &mut *t__x3, &mut *t__x4, &mut *t__y1, &mut *t__y2, &mut *t__y3, &mut *t__y4, &mut *t__z1, &mut *t__xc, &mut *t__yc, &mut *t__tcolor)) {
        __rt.pset((*t__xc), (*t__yc), __rt.bg_color as f64);
        let __stpx2 = __rt.cur_x() + (0_f64);
        let __stpy2 = __rt.cur_y() + (0_f64);
        __rt.paint(__stpx2, __stpy2, back, border);
        let __stpx3 = __rt.cur_x() + (0_f64);
        let __stpy3 = __rt.cur_y() + (0_f64);
        __rt.paint(__stpx3, __stpy3, (*t__tcolor), border);
    }
    if qb_bool(qb_from_bool(__gs.tor__bord == "YES")) {
        border = back;
    } else {
        border = (*t__tcolor);
    }
    __rt.line((*t__x1),(*t__y1),(*t__x2),(*t__y2),border);
    __rt.line_to((*t__x3),(*t__y3),border);
    __rt.line_to((*t__x4),(*t__y4),border);
    __rt.line_to((*t__x1),(*t__y1),border);
}

fn toruscalc(__rt: &mut Runtime, __gs: &mut GameState, t__x1: &mut Vec<f64>, t__x2: &mut Vec<f64>, t__x3: &mut Vec<f64>, t__x4: &mut Vec<f64>, t__y1: &mut Vec<f64>, t__y2: &mut Vec<f64>, t__y3: &mut Vec<f64>, t__y4: &mut Vec<f64>, t__z1: &mut Vec<f64>, t__xc: &mut Vec<f64>, t__yc: &mut Vec<f64>, t__tcolor: &mut Vec<f64>) {
    let mut xsect: f64 = 0.0_f64;
    let mut ypanel: f64 = 0.0_f64;
    let mut xrot: f64 = 0.0_f64;
    let mut yrot: f64 = 0.0_f64;
    let mut cxrot: f64 = 0.0_f64;
    let mut sxrot: f64 = 0.0_f64;
    let mut cyrot: f64 = 0.0_f64;
    let mut syrot: f64 = 0.0_f64;
    let mut xinc: f64 = 0.0_f64;
    let mut yinc: f64 = 0.0_f64;
    let mut firsty: f64 = 0.0_f64;
    let mut sx: f64 = 0.0_f64;
    let mut sy: f64 = 0.0_f64;
    let mut sz: f64 = 0.0_f64;
    let mut ssx: f64 = 0.0_f64;
    let mut ty: f64 = 0.0_f64;
    let mut tz: f64 = 0.0_f64;

    let mut xsect: f64 = Default::default();
    let mut ypanel: f64 = Default::default();
    let __fa4 = __gs.tor__xdegree;
    let __tmp5 = degtorad(__rt, __gs, __fa4);
    xrot = __tmp5;
    let __fa6 = __gs.tor__ydegree;
    let __tmp7 = degtorad(__rt, __gs, __fa6);
    yrot = __tmp7;
    cxrot = qb_cos(xrot);
    sxrot = qb_sin(xrot);
    cyrot = qb_cos(yrot);
    syrot = qb_sin(yrot);
    xinc = ((2_f64 * pi) / __gs.tor__sect);
    yinc = ((2_f64 * pi) / __gs.tor__panel);
    firsty = ((__gs.tor__thick + 1_f64) * cyrot);
    t__x1[(0_f64) as usize] = firsty;
    t__x2[((__gs.tor__sect - 1_f64)) as usize] = firsty;
    t__x3[((__gs.max - 1_f64)) as usize] = firsty;
    t__x4[((__gs.max - __gs.tor__sect)) as usize] = firsty;
    t__y1[(0_f64) as usize] = 0_f64;
    t__y2[((__gs.tor__sect - 1_f64)) as usize] = 0_f64;
    t__y3[((__gs.max - 1_f64)) as usize] = 0_f64;
    t__y4[((__gs.max - __gs.tor__sect)) as usize] = 0_f64;
    t__z1[(0_f64) as usize] = ((-(__gs.tor__thick + 1_f64)) * syrot);
    xsect = 1_f64;
    let __for_to_xsect: f64 = (__gs.tor__sect - 1_f64);
    let __for_step_xsect: f64 = 1.0_f64;
    while (__for_step_xsect > 0.0 && xsect <= __for_to_xsect) || (__for_step_xsect < 0.0 && xsect >= __for_to_xsect) {
        sx = ((__gs.tor__thick + 1_f64) * qb_cos((xsect * xinc)));
        sy = (((__gs.tor__thick + 1_f64) * qb_sin((xsect * xinc))) * cxrot);
        sz = (((__gs.tor__thick + 1_f64) * qb_sin((xsect * xinc))) * sxrot);
        ssx = ((sz * syrot) + (sx * cyrot));
        t__x1[(xsect) as usize] = ssx;
        t__x2[((xsect - 1_f64)) as usize] = ssx;
        t__x3[((((__gs.max - __gs.tor__sect) + xsect) - 1_f64)) as usize] = ssx;
        t__x4[(((__gs.max - __gs.tor__sect) + xsect)) as usize] = ssx;
        t__y1[(xsect) as usize] = sy;
        t__y2[((xsect - 1_f64)) as usize] = sy;
        t__y3[((((__gs.max - __gs.tor__sect) + xsect) - 1_f64)) as usize] = sy;
        t__y4[(((__gs.max - __gs.tor__sect) + xsect)) as usize] = sy;
        t__z1[(xsect) as usize] = ((sz * cyrot) - (sx * syrot));
        xsect += __for_step_xsect;
    }
    ypanel = 1_f64;
    let __for_to_ypanel: f64 = (__gs.tor__panel - 1_f64);
    let __for_step_ypanel: f64 = 1.0_f64;
    while (__for_step_ypanel > 0.0 && ypanel <= __for_to_ypanel) || (__for_step_ypanel < 0.0 && ypanel >= __for_to_ypanel) {
        sx = (__gs.tor__thick + qb_cos((ypanel * yinc)));
        sy = ((-qb_sin((ypanel * yinc))) * sxrot);
        sz = (qb_sin((ypanel * yinc)) * cxrot);
        ssx = ((sz * syrot) + (sx * cyrot));
        t__x1[((__gs.tor__sect * ypanel)) as usize] = ssx;
        t__x2[(((__gs.tor__sect * (ypanel + 1_f64)) - 1_f64)) as usize] = ssx;
        t__x3[(((__gs.tor__sect * ypanel) - 1_f64)) as usize] = ssx;
        t__x4[((__gs.tor__sect * (ypanel - 1_f64))) as usize] = ssx;
        t__y1[((__gs.tor__sect * ypanel)) as usize] = sy;
        t__y2[(((__gs.tor__sect * (ypanel + 1_f64)) - 1_f64)) as usize] = sy;
        t__y3[(((__gs.tor__sect * ypanel) - 1_f64)) as usize] = sy;
        t__y4[((__gs.tor__sect * (ypanel - 1_f64))) as usize] = sy;
        t__z1[((__gs.tor__sect * ypanel)) as usize] = ((sz * cyrot) - (sx * syrot));
        xsect = 1_f64;
        let __for_to_xsect: f64 = (__gs.tor__sect - 1_f64);
        let __for_step_xsect: f64 = 1.0_f64;
        while (__for_step_xsect > 0.0 && xsect <= __for_to_xsect) || (__for_step_xsect < 0.0 && xsect >= __for_to_xsect) {
            counttiles(__rt, __gs, &mut xsect, &mut ypanel);
            ty = ((__gs.tor__thick + qb_cos((ypanel * yinc))) * qb_sin((xsect * xinc)));
            tz = qb_sin((ypanel * yinc));
            sx = ((__gs.tor__thick + qb_cos((ypanel * yinc))) * qb_cos((xsect * xinc)));
            sy = ((ty * cxrot) - (tz * sxrot));
            sz = ((ty * sxrot) + (tz * cxrot));
            ssx = ((sz * syrot) + (sx * cyrot));
            t__x1[(((__gs.tor__sect * ypanel) + xsect)) as usize] = ssx;
            t__x2[((((__gs.tor__sect * ypanel) + xsect) - 1_f64)) as usize] = ssx;
            t__x3[((((__gs.tor__sect * (ypanel - 1_f64)) + xsect) - 1_f64)) as usize] = ssx;
            t__x4[(((__gs.tor__sect * (ypanel - 1_f64)) + xsect)) as usize] = ssx;
            t__y1[(((__gs.tor__sect * ypanel) + xsect)) as usize] = sy;
            t__y2[((((__gs.tor__sect * ypanel) + xsect) - 1_f64)) as usize] = sy;
            t__y3[((((__gs.tor__sect * (ypanel - 1_f64)) + xsect) - 1_f64)) as usize] = sy;
            t__y4[(((__gs.tor__sect * (ypanel - 1_f64)) + xsect)) as usize] = sy;
            t__z1[(((__gs.tor__sect * ypanel) + xsect)) as usize] = ((sz * cyrot) - (sx * syrot));
            xsect += __for_step_xsect;
        }
        ypanel += __for_step_ypanel;
    }
    let mut __tmp_num8: f64 = (-1_f64);
    let mut __tmp_num9: f64 = (-1_f64);
    counttiles(__rt, __gs, &mut __tmp_num8, &mut __tmp_num9);
}

fn toruscolor(__rt: &mut Runtime, __gs: &mut GameState, t__x1: &mut Vec<f64>, t__x2: &mut Vec<f64>, t__x3: &mut Vec<f64>, t__x4: &mut Vec<f64>, t__y1: &mut Vec<f64>, t__y2: &mut Vec<f64>, t__y3: &mut Vec<f64>, t__y4: &mut Vec<f64>, t__z1: &mut Vec<f64>, t__xc: &mut Vec<f64>, t__yc: &mut Vec<f64>, t__tcolor: &mut Vec<f64>) {
    let mut lastatr: f64 = 0.0_f64;
    let mut atr: f64 = 0.0_f64;
    let mut til: f64 = 0.0_f64;

    lastatr = (__gs.vc__atribs - 2_f64);
    atr = 1_f64;
    til = 0_f64;
    let __for_to_til: f64 = (__gs.max - 1_f64);
    let __for_step_til: f64 = 1.0_f64;
    while (__for_step_til > 0.0 && til <= __for_to_til) || (__for_step_til < 0.0 && til >= __for_to_til) {
        if qb_bool(qb_from_bool(atr >= lastatr)) {
            atr = 1_f64;
        } else {
            atr = (atr + 1_f64);
        }
        t__tcolor[(til) as usize] = atr;
        til += __for_step_til;
    }
}

fn torusdefine(__rt: &mut Runtime, __gs: &mut GameState) {
    let mut available_s: String = String::new();
    let mut fields: f64 = 0.0_f64;
    let mut ky: f64 = 0.0_f64;
    let mut fld: f64 = 0.0_f64;
    let mut k_s: String = String::new();
    let mut inc: f64 = 0.0_f64;
    let mut i: f64 = 0.0_f64;

    let enter: f64 = 13_f64;
    let escape: f64 = 27_f64;
    let downarrow: f64 = 80_f64;
    let uparrow: f64 = 72_f64;
    let leftarrow: f64 = 75_f64;
    let rightarrow: f64 = 77_f64;
    let col1: f64 = 20_f64;
    let col2: f64 = 50_f64;
    let row: f64 = 9_f64;
    __rt.locate(Some(1_f64), Some(col1), None);
    __rt.println(&[qb_str(&("UP .............. Move to next field"))]);
    __rt.locate(Some(2_f64), Some(col1), None);
    __rt.println(&[qb_str(&("DOWN ........ Move to previous field"))]);
    __rt.locate(Some(3_f64), Some(col1), None);
    __rt.println(&[qb_str(&("LEFT ......... Rotate field value up"))]);
    __rt.locate(Some(4_f64), Some(col1), None);
    __rt.println(&[qb_str(&("RIGHT ...... Rotate field value down"))]);
    __rt.locate(Some(5_f64), Some(col1), None);
    __rt.println(&[qb_str(&("ENTER .... Start with current values"))]);
    __rt.locate(Some(6_f64), Some(col1), None);
    __rt.println(&[qb_str(&("ESCAPE .................. Quit Torus"))]);
    __rt.locate(Some(row), Some(col1), Some(1_f64));
    __rt.locate(Some(row), Some(col1), None);
    __rt.print(&[qb_str(&("Thickness"))]);
    __rt.locate(Some(row), Some(col2), None);
    let __pu10 = qb_print_using(&("[ # ]"), &[QbVal::Num(__gs.tor__thick)]);
    __rt.print(&[__pu10]);
    __rt.locate(Some((row + 2_f64)), Some(col1), None);
    __rt.print(&[qb_str(&("Panels per Section"))]);
    __rt.locate(Some((row + 2_f64)), Some(col2), None);
    let __pu11 = qb_print_using(&("[ ## ]"), &[QbVal::Num(__gs.tor__panel)]);
    __rt.print(&[__pu11]);
    __rt.locate(Some((row + 4_f64)), Some(col1), None);
    __rt.print(&[qb_str(&("Sections per Torus"))]);
    __rt.locate(Some((row + 4_f64)), Some(col2), None);
    let __pu12 = qb_print_using(&("[ ## ]"), &[QbVal::Num(__gs.tor__sect)]);
    __rt.print(&[__pu12]);
    __rt.locate(Some((row + 6_f64)), Some(col1), None);
    __rt.print(&[qb_str(&("Tilt around Horizontal Axis"))]);
    __rt.locate(Some((row + 6_f64)), Some(col2), None);
    let __pu13 = qb_print_using(&("[ ### ]"), &[QbVal::Num(__gs.tor__xdegree)]);
    __rt.print(&[__pu13]);
    __rt.locate(Some((row + 8_f64)), Some(col1), None);
    __rt.print(&[qb_str(&("Tilt around Vertical Axis"))]);
    __rt.locate(Some((row + 8_f64)), Some(col2), None);
    let __pu14 = qb_print_using(&("[ ### ]"), &[QbVal::Num(__gs.tor__ydegree)]);
    __rt.print(&[__pu14]);
    __rt.locate(Some((row + 10_f64)), Some(col1), None);
    __rt.print(&[qb_str(&("Tile Border"))]);
    __rt.locate(Some((row + 10_f64)), Some(col2), None);
    let __pu_s15 = (__gs.tor__bord).to_string();
    let __pu16 = qb_print_using(&("[ & ] "), &[QbVal::Str(&__pu_s15)]);
    __rt.print(&[__pu16]);
    __rt.locate(Some((row + 12_f64)), Some(col1), None);
    __rt.print(&[qb_str(&("Screen Mode"))]);
    __rt.locate(Some((row + 12_f64)), Some(col2), None);
    let __pu17 = qb_print_using(&("[ ## ]"), &[QbVal::Num(__gs.vc__scrn)]);
    __rt.println(&[__pu17]);
    if qb_bool(qb_from_bool(qb_len(&(__gs.available)) == 1_f64)) {
        fields = 10_f64;
    } else {
        fields = 12_f64;
    }
    loop {
        __rt.locate(Some((row + fld)), Some((col2 + 2_f64)), None);
        loop {
            let __tmp18 = __rt.inkey();
            k_s = (__tmp18).to_string();
            if !qb_bool(qb_from_bool((k_s).as_str() == "")) { break; }
        }
        ky = qb_asc(&(qb_right(&(k_s), 1_f64)));
        let __sel = ky;
        if __sel == escape {
            __rt.cls(0u8);
            __rt.quit();
        } else if __sel == uparrow || __sel == downarrow {
            if qb_bool(qb_from_bool(ky == downarrow)) {
                inc = 2_f64;
            } else {
                inc = (-2_f64);
            }
            let __tmp19 = rotated(__rt, __gs, 0_f64, fields, fld, inc);
            fld = __tmp19;
        } else if __sel == rightarrow || __sel == leftarrow {
            if qb_bool(qb_from_bool(ky == rightarrow)) {
                inc = 1_f64;
            } else {
                inc = (-1_f64);
            }
            let __sel = fld;
            if __sel == 0_f64 {
                let __fa20 = qb_int(__gs.tor__thick);
                let __tmp21 = rotated(__rt, __gs, 1_f64, 9_f64, __fa20, inc);
                __gs.tor__thick = __tmp21;
                let __pu22 = qb_print_using(&("#"), &[QbVal::Num(__gs.tor__thick)]);
                __rt.println(&[__pu22]);
            } else if __sel == 2_f64 {
                let __fa23 = __gs.tor__panel;
                let __tmp24 = rotated(__rt, __gs, 6_f64, 20_f64, __fa23, inc);
                __gs.tor__panel = __tmp24;
                let __pu25 = qb_print_using(&("##"), &[QbVal::Num(__gs.tor__panel)]);
                __rt.println(&[__pu25]);
            } else if __sel == 4_f64 {
                let __fa26 = __gs.tor__sect;
                let __tmp27 = rotated(__rt, __gs, 6_f64, 20_f64, __fa26, inc);
                __gs.tor__sect = __tmp27;
                let __pu28 = qb_print_using(&("##"), &[QbVal::Num(__gs.tor__sect)]);
                __rt.println(&[__pu28]);
            } else if __sel == 6_f64 {
                let __fa29 = __gs.tor__xdegree;
                let __tmp30 = rotated(__rt, __gs, 0_f64, 345_f64, __fa29, (15_f64 * inc));
                __gs.tor__xdegree = __tmp30;
                let __pu31 = qb_print_using(&("###"), &[QbVal::Num(__gs.tor__xdegree)]);
                __rt.println(&[__pu31]);
            } else if __sel == 8_f64 {
                let __fa32 = __gs.tor__ydegree;
                let __tmp33 = rotated(__rt, __gs, 0_f64, 345_f64, __fa32, (15_f64 * inc));
                __gs.tor__ydegree = __tmp33;
                let __pu34 = qb_print_using(&("###"), &[QbVal::Num(__gs.tor__ydegree)]);
                __rt.println(&[__pu34]);
            } else if __sel == 10_f64 {
                if qb_bool(qb_from_bool(__gs.vc__atribs > 2_f64)) {
                    if qb_bool(qb_from_bool(__gs.tor__bord == "YES")) {
                        __gs.tor__bord = ("NO").to_string();
                    } else {
                        __gs.tor__bord = ("YES").to_string();
                    }
                }
                __rt.println(&[qb_str(&(__gs.tor__bord))]);
            } else if __sel == 12_f64 {
                i = qb_instr(1.0, &(__gs.available), &(qb_hex(__gs.vc__scrn)));
                let __fa35 = qb_len(&(__gs.available));
                let __tmp36 = rotated(__rt, __gs, 1_f64, __fa35, i, inc);
                i = __tmp36;
                __gs.vc__scrn = qb_val(&(format!("{}{}" ,"&h",qb_mid(&(__gs.available), i, Some(1_f64)))));
                let __pu37 = qb_print_using(&("##"), &[QbVal::Num(__gs.vc__scrn)]);
                __rt.println(&[__pu37]);
            } else {
            }
        } else {
        }
        let mut __tmp_num38: f64 = __gs.vc__scrn;
        setconfig(__rt, __gs, &mut __tmp_num38);
        if qb_bool(qb_from_bool(ky == enter)) { break; }
    }
    __rt.locate(Some(1_f64), Some(1_f64), Some(0_f64));
    let __sel = __gs.vc__scrn;
    if __sel == 1_f64 {
        __gs.tor__delay = 0.3_f64;
    } else if __sel == 2_f64 || __sel == 3_f64 || __sel == 10_f64 || __sel == 11_f64 || __sel == 13_f64 {
        __gs.tor__delay = 0_f64;
    } else {
        __gs.tor__delay = 0.05_f64;
    }
    __rt.randomize(qb_timer());
}

fn torusdraw(__rt: &mut Runtime, __gs: &mut GameState, t__x1: &mut Vec<f64>, t__x2: &mut Vec<f64>, t__x3: &mut Vec<f64>, t__x4: &mut Vec<f64>, t__y1: &mut Vec<f64>, t__y2: &mut Vec<f64>, t__y3: &mut Vec<f64>, t__y4: &mut Vec<f64>, t__z1: &mut Vec<f64>, t__xc: &mut Vec<f64>, t__yc: &mut Vec<f64>, t__tcolor: &mut Vec<f64>, index: &mut Vec<f64>) {
    let mut til: f64 = 0.0_f64;

    til = 0_f64;
    let __for_to_til: f64 = (__gs.max - 1_f64);
    let __for_step_til: f64 = 1.0_f64;
    while (__for_step_til > 0.0 && til <= __for_to_til) || (__for_step_til < 0.0 && til >= __for_to_til) {
        let __taidx39 = (index[(til) as usize]) as usize;
        tiledraw(__rt, __gs, &mut t__x1[__taidx39], &mut t__x2[__taidx39], &mut t__x3[__taidx39], &mut t__x4[__taidx39], &mut t__y1[__taidx39], &mut t__y2[__taidx39], &mut t__y3[__taidx39], &mut t__y4[__taidx39], &mut t__z1[__taidx39], &mut t__xc[__taidx39], &mut t__yc[__taidx39], &mut t__tcolor[__taidx39]);
        til += __for_step_til;
    }
}

fn torusrotate(__rt: &mut Runtime, __gs: &mut GameState, first: &mut f64) {
    let mut temp: f64 = 0.0_f64;
    let mut firstclr: f64 = 0.0_f64;
    let mut lastclr: f64 = 0.0_f64;
    let mut lastatr: f64 = 0.0_f64;
    let mut work: f64 = 0.0_f64;
    let mut atr: f64 = 0.0_f64;
    let mut i: f64 = 0.0_f64;
    let mut toggle: f64 = 0.0_f64;

    let mut temp: f64 = Default::default();
    if qb_bool(__gs.vc__colors) {
        let __sel = (*first);
        if __sel == rndm {
            let __tmp40 = __rt.rnd();
            firstclr = qb_int((__tmp40 * __gs.vc__colors));
        } else if __sel == start {
            firstclr = 0_f64;
        } else {
            firstclr = (firstclr - 1_f64);
        }
        if qb_bool(qb_from_bool(__gs.vc__colors > (__gs.max - 1_f64))) {
            lastclr = (__gs.max - 1_f64);
        } else {
            lastclr = (__gs.vc__colors - 1_f64);
        }
        if qb_bool(qb_or(qb_from_bool(firstclr < 0_f64), qb_from_bool(firstclr >= lastclr))) {
            firstclr = lastclr;
        }
        if qb_bool(qb_from_bool(__gs.vc__atribs == 2_f64)) {
            lastatr = (__gs.vc__atribs - 1_f64);
        } else {
            if qb_bool(qb_from_bool(lastclr < (__gs.vc__atribs - 2_f64))) {
                lastatr = lastclr;
            } else {
                lastatr = (__gs.vc__atribs - 2_f64);
            }
        }
        work = firstclr;
        atr = lastatr;
        let __for_to_atr: f64 = 1_f64;
        let __for_step_atr: f64 = (-1_f64);
        while (__for_step_atr > 0.0 && atr <= __for_to_atr) || (__for_step_atr < 0.0 && atr >= __for_to_atr) {
            __rt.palette(atr, __gs.pal[(work) as usize]);
            work = (work - 1_f64);
            if qb_bool(qb_from_bool(work < 0_f64)) {
                work = lastclr;
            }
            atr += __for_step_atr;
        }
    }
    if qb_bool(qb_from_bool(__gs.vc__atribs == 2_f64)) {
        i = 0_f64;
        let __for_to_i: f64 = (__gs.max - 1_f64);
        let __for_step_i: f64 = 1.0_f64;
        while (__for_step_i > 0.0 && i <= __for_to_i) || (__for_step_i < 0.0 && i >= __for_to_i) {
            __gs.t__tcolor[(i) as usize] = toggle;
            i += __for_step_i;
        }
        let mut __taf41 = std::mem::take(&mut __gs.t__x1);
        let mut __taf42 = std::mem::take(&mut __gs.t__x2);
        let mut __taf43 = std::mem::take(&mut __gs.t__x3);
        let mut __taf44 = std::mem::take(&mut __gs.t__x4);
        let mut __taf45 = std::mem::take(&mut __gs.t__y1);
        let mut __taf46 = std::mem::take(&mut __gs.t__y2);
        let mut __taf47 = std::mem::take(&mut __gs.t__y3);
        let mut __taf48 = std::mem::take(&mut __gs.t__y4);
        let mut __taf49 = std::mem::take(&mut __gs.t__z1);
        let mut __taf50 = std::mem::take(&mut __gs.t__xc);
        let mut __taf51 = std::mem::take(&mut __gs.t__yc);
        let mut __taf52 = std::mem::take(&mut __gs.t__tcolor);
        let mut __saf53 = std::mem::take(&mut __gs.index);
        torusdraw(__rt, __gs, &mut __taf41, &mut __taf42, &mut __taf43, &mut __taf44, &mut __taf45, &mut __taf46, &mut __taf47, &mut __taf48, &mut __taf49, &mut __taf50, &mut __taf51, &mut __taf52, &mut __saf53);
        __gs.t__x1 = __taf41;
        __gs.t__x2 = __taf42;
        __gs.t__x3 = __taf43;
        __gs.t__x4 = __taf44;
        __gs.t__y1 = __taf45;
        __gs.t__y2 = __taf46;
        __gs.t__y3 = __taf47;
        __gs.t__y4 = __taf48;
        __gs.t__z1 = __taf49;
        __gs.t__xc = __taf50;
        __gs.t__yc = __taf51;
        __gs.t__tcolor = __taf52;
        __gs.index = __saf53;
        toggle = qb_mod((toggle + 1_f64), 2_f64);
    }
    if qb_bool(qb_and(qb_from_bool(__gs.vc__scrn == 1_f64), qb_or(qb_from_bool(__gs.bestmode == cga), qb_from_bool(__gs.bestmode == mcga)))) {
        __rt.color(7.0_f64, Some(toggle));
        toggle = qb_mod((toggle + 1_f64), 2_f64);
        return; // EXIT SUB
    }
}

fn torussort(__rt: &mut Runtime, __gs: &mut GameState, low: &mut f64, high: &mut f64) {
    let mut partition: f64 = 0.0_f64;
    let mut randindex: f64 = 0.0_f64;
    let mut i: f64 = 0.0_f64;
    let mut j: f64 = 0.0_f64;

    let mut partition: f64 = Default::default();
    if qb_bool(qb_from_bool((*low) < (*high))) {
        if qb_bool(qb_from_bool(((*high) - (*low)) == 1_f64)) {
            if qb_bool(qb_from_bool(__gs.t__z1[(__gs.index[((*low)) as usize]) as usize] > __gs.t__z1[(__gs.index[((*high)) as usize]) as usize])) {
                counttiles(__rt, __gs, high, low);
                __gs.index.swap(((*low)) as usize, ((*high)) as usize);
            }
        } else {
            let __tmp54 = __rt.rnd();
            randindex = (qb_int((__tmp54 * (((*high) - (*low)) + 1_f64))) + (*low));
            counttiles(__rt, __gs, high, low);
            __gs.index.swap(((*high)) as usize, (randindex) as usize);
            partition = __gs.t__z1[(__gs.index[((*high)) as usize]) as usize];
            loop {
                i = (*low);
                j = (*high);
                while qb_bool(qb_and(qb_from_bool(i < j), qb_from_bool(__gs.t__z1[(__gs.index[(i) as usize]) as usize] <= partition))) {
                    i = (i + 1_f64);
                }
                while qb_bool(qb_and(qb_from_bool(j > i), qb_from_bool(__gs.t__z1[(__gs.index[(j) as usize]) as usize] >= partition))) {
                    j = (j - 1_f64);
                }
                if qb_bool(qb_from_bool(i < j)) {
                    counttiles(__rt, __gs, high, low);
                    __gs.index.swap((i) as usize, (j) as usize);
                }
                if !qb_bool(qb_from_bool(i < j)) { break; }
            }
            counttiles(__rt, __gs, high, low);
            __gs.index.swap((i) as usize, ((*high)) as usize);
            if qb_bool(qb_from_bool((i - (*low)) < ((*high) - i))) {
                let mut __tmp_num55: f64 = (i - 1_f64);
                torussort(__rt, __gs, low, &mut __tmp_num55);
                let mut __tmp_num56: f64 = (i + 1_f64);
                torussort(__rt, __gs, &mut __tmp_num56, high);
            } else {
                let mut __tmp_num57: f64 = (i + 1_f64);
                torussort(__rt, __gs, &mut __tmp_num57, high);
                let mut __tmp_num58: f64 = (i - 1_f64);
                torussort(__rt, __gs, low, &mut __tmp_num58);
            }
        }
    }
}

fn degtorad(__rt: &mut Runtime, __gs: &mut GameState, mut degrees: f64) -> f64 {
    let mut __fn_ret: f64 = Default::default();
    __fn_ret = (((degrees * 2_f64) * pi) / 360_f64);
    __fn_ret
}

fn inside(__rt: &mut Runtime, __gs: &mut GameState, t__x1: &mut f64, t__x2: &mut f64, t__x3: &mut f64, t__x4: &mut f64, t__y1: &mut f64, t__y2: &mut f64, t__y3: &mut f64, t__y4: &mut f64, t__z1: &mut f64, t__xc: &mut f64, t__yc: &mut f64, t__tcolor: &mut f64) -> f64 {
    let mut __fn_ret: f64 = Default::default();
    let mut highest: f64 = 0.0_f64;
    let mut lowest: f64 = 0.0_f64;
    let mut border: f64 = 0.0_f64;
    let mut x: f64 = 0.0_f64;
    let mut yu: f64 = 0.0_f64;
    let mut yd: f64 = 0.0_f64;
    let mut h: f64 = 0.0_f64;
    let mut l: f64 = 0.0_f64;
    let mut isup: f64 = 0.0_f64;
    let mut isdown: f64 = 0.0_f64;

    let mut highest: f64 = Default::default();
    let mut lowest: f64 = Default::default();
    border = (__gs.vc__atribs - 1_f64);
    (*t__xc) = ((*t__x2) + ((((*t__x3) + (((*t__x4) - (*t__x3)) / 2_f64)) - (*t__x2)) / 2_f64));
    (*t__yc) = ((*t__y2) + ((((*t__y3) + (((*t__y4) - (*t__y3)) / 2_f64)) - (*t__y2)) / 2_f64));
    if qb_bool(qb_from_bool(__rt.point((*t__xc), (*t__yc)) == border)) {
        __fn_ret = qb_false;
        return __fn_ret; // EXIT FUNCTION
    }
    highest = (*t__y1);
    lowest = (*t__y1);
    if qb_bool(qb_from_bool((*t__y2) > highest)) {
        highest = (*t__y2);
    }
    if qb_bool(qb_from_bool((*t__y2) < lowest)) {
        lowest = (*t__y2);
    }
    if qb_bool(qb_from_bool((*t__y3) > highest)) {
        highest = (*t__y3);
    }
    if qb_bool(qb_from_bool((*t__y3) < lowest)) {
        lowest = (*t__y3);
    }
    if qb_bool(qb_from_bool((*t__y4) > highest)) {
        highest = (*t__y4);
    }
    if qb_bool(qb_from_bool((*t__y4) < lowest)) {
        lowest = (*t__y4);
    }
    let __tmp59 = __rt.pmap((*t__xc), 0_f64);
    x = __tmp59;
    let __tmp60 = __rt.pmap((*t__yc), 1_f64);
    yu = __tmp60;
    yd = yu;
    let __tmp61 = __rt.pmap(highest, 1_f64);
    h = __tmp61;
    let __tmp62 = __rt.pmap(lowest, 1_f64);
    l = __tmp62;
    isup = qb_false;
    isdown = qb_false;
    loop {
        yu = (yu - 1_f64);
        yd = (yd + 1_f64);
        if qb_bool(qb_not(isup)) {
            if qb_bool(qb_from_bool(__rt.point((*t__xc), __rt.pmap(yu, 3_f64)) == border)) {
                isup = qb_true;
            }
        }
        if qb_bool(qb_not(isdown)) {
            if qb_bool(qb_from_bool(__rt.point((*t__xc), __rt.pmap(yd, 3_f64)) == border)) {
                isdown = qb_true;
            }
        }
        if qb_bool(qb_and(isup, isdown)) {
            __fn_ret = qb_true;
            return __fn_ret; // EXIT FUNCTION
        }
        if qb_bool(qb_and(qb_from_bool(yd > l), qb_from_bool(yu < h))) { break; }
    }
    __fn_ret = qb_false;
    __fn_ret
}

fn rotated(__rt: &mut Runtime, __gs: &mut GameState, mut lower: f64, mut upper: f64, mut current: f64, mut inc: f64) -> f64 {
    let mut __fn_ret: f64 = Default::default();
    current = (current + inc);
    if qb_bool(qb_from_bool(current > upper)) {
        current = lower;
    }
    if qb_bool(qb_from_bool(current < lower)) {
        current = upper;
    }
    __fn_ret = current;
    __fn_ret
}

fn memerr(__rt: &mut Runtime, __gs: &mut GameState) {
    __rt.locate(Some(22_f64), Some(1_f64), None);
    __rt.println(&[qb_str(&("Out of memory"))]);
    __rt.println(&[qb_str(&("Reducing panels from")), qb_print_num(__gs.tor__panel), qb_str(&("to")), qb_print_num((__gs.tor__panel - 1_f64))]);
    __rt.print(&[qb_str(&("Reducing sections from")), qb_print_num(__gs.tor__sect), qb_str(&("to")), qb_print_num((__gs.tor__sect - 1_f64))]);
    while qb_bool(qb_from_bool((__rt.inkey()).as_str() == "")) {
    }
    __gs.tor__panel = (__gs.tor__panel - 1_f64);
    __gs.tor__sect = (__gs.tor__sect - 1_f64);
    __rt.error_pending = false;
    // label: RowErr
    if qb_bool(qb_from_bool(__gs.initrows == 50_f64)) {
        __gs.initrows = 43_f64;
        __rt.error_pending = false;
    } else {
        __gs.initrows = 25_f64;
        __rt.error_pending = false;
    }
}

fn main() {
    let mut __rt = Runtime::new();
    let mut __gs = GameState::default();

    let mut available_s: String = String::new();
    let mut tmp: f64 = 0.0_f64;
    let mut til: f64 = 0.0_f64;

    __gs.pal = vec![Default::default(); (300_f64+1.0) as usize];
    __gs.tor__thick = 3_f64;
    __gs.tor__bord = ("YES").to_string();
    __gs.tor__panel = 8_f64;
    __gs.tor__sect = 14_f64;
    __gs.tor__xdegree = 60_f64;
    __gs.tor__ydegree = 165_f64;
    getconfig(&mut __rt, &mut __gs);
    __gs.vc__scrn = __gs.bestmode;
    while qb_bool(qb_true) {
        torusdefine(&mut __rt, &mut __gs);
        loop {
            tmp = __gs.tor__panel;
            __gs.max = (__gs.tor__panel * __gs.tor__sect);
            __gs.index.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__x1.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__x2.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__x3.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__x4.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__y1.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__y2.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__y3.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__y4.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__z1.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__xc.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__yc.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            __gs.t__tcolor.resize(((__gs.max - 1_f64)+1.0) as usize, Default::default());
            if qb_bool(qb_from_bool(tmp == __gs.tor__panel)) { break; }
        }
        til = 0_f64;
        let __for_to_til: f64 = (__gs.max - 1_f64);
        let __for_step_til: f64 = 1.0_f64;
        while (__for_step_til > 0.0 && til <= __for_to_til) || (__for_step_til < 0.0 && til >= __for_to_til) {
            __gs.index[(til) as usize] = til;
            til += __for_step_til;
        }
        let mut __tmp_str63 = ("Calculating").to_string();
        message(&mut __rt, &mut __gs, &mut __tmp_str63);
        let mut __taf64 = std::mem::take(&mut __gs.t__x1);
        let mut __taf65 = std::mem::take(&mut __gs.t__x2);
        let mut __taf66 = std::mem::take(&mut __gs.t__x3);
        let mut __taf67 = std::mem::take(&mut __gs.t__x4);
        let mut __taf68 = std::mem::take(&mut __gs.t__y1);
        let mut __taf69 = std::mem::take(&mut __gs.t__y2);
        let mut __taf70 = std::mem::take(&mut __gs.t__y3);
        let mut __taf71 = std::mem::take(&mut __gs.t__y4);
        let mut __taf72 = std::mem::take(&mut __gs.t__z1);
        let mut __taf73 = std::mem::take(&mut __gs.t__xc);
        let mut __taf74 = std::mem::take(&mut __gs.t__yc);
        let mut __taf75 = std::mem::take(&mut __gs.t__tcolor);
        toruscalc(&mut __rt, &mut __gs, &mut __taf64, &mut __taf65, &mut __taf66, &mut __taf67, &mut __taf68, &mut __taf69, &mut __taf70, &mut __taf71, &mut __taf72, &mut __taf73, &mut __taf74, &mut __taf75);
        __gs.t__x1 = __taf64;
        __gs.t__x2 = __taf65;
        __gs.t__x3 = __taf66;
        __gs.t__x4 = __taf67;
        __gs.t__y1 = __taf68;
        __gs.t__y2 = __taf69;
        __gs.t__y3 = __taf70;
        __gs.t__y4 = __taf71;
        __gs.t__z1 = __taf72;
        __gs.t__xc = __taf73;
        __gs.t__yc = __taf74;
        __gs.t__tcolor = __taf75;
        let mut __taf76 = std::mem::take(&mut __gs.t__x1);
        let mut __taf77 = std::mem::take(&mut __gs.t__x2);
        let mut __taf78 = std::mem::take(&mut __gs.t__x3);
        let mut __taf79 = std::mem::take(&mut __gs.t__x4);
        let mut __taf80 = std::mem::take(&mut __gs.t__y1);
        let mut __taf81 = std::mem::take(&mut __gs.t__y2);
        let mut __taf82 = std::mem::take(&mut __gs.t__y3);
        let mut __taf83 = std::mem::take(&mut __gs.t__y4);
        let mut __taf84 = std::mem::take(&mut __gs.t__z1);
        let mut __taf85 = std::mem::take(&mut __gs.t__xc);
        let mut __taf86 = std::mem::take(&mut __gs.t__yc);
        let mut __taf87 = std::mem::take(&mut __gs.t__tcolor);
        toruscolor(&mut __rt, &mut __gs, &mut __taf76, &mut __taf77, &mut __taf78, &mut __taf79, &mut __taf80, &mut __taf81, &mut __taf82, &mut __taf83, &mut __taf84, &mut __taf85, &mut __taf86, &mut __taf87);
        __gs.t__x1 = __taf76;
        __gs.t__x2 = __taf77;
        __gs.t__x3 = __taf78;
        __gs.t__x4 = __taf79;
        __gs.t__y1 = __taf80;
        __gs.t__y2 = __taf81;
        __gs.t__y3 = __taf82;
        __gs.t__y4 = __taf83;
        __gs.t__z1 = __taf84;
        __gs.t__xc = __taf85;
        __gs.t__yc = __taf86;
        __gs.t__tcolor = __taf87;
        let mut __tmp_str88 = ("Sorting").to_string();
        message(&mut __rt, &mut __gs, &mut __tmp_str88);
        let mut __tmp_num89: f64 = 0_f64;
        let mut __tmp_num90: f64 = (__gs.max - 1_f64);
        torussort(&mut __rt, &mut __gs, &mut __tmp_num89, &mut __tmp_num90);
        __rt.screen(__gs.vc__scrn);
        setpalette(&mut __rt, &mut __gs);
        __rt.set_window((-(__gs.tor__thick + 1_f64)),(-(__gs.tor__thick + 1_f64)),(__gs.tor__thick + 1_f64),(__gs.tor__thick + 1_f64),false);
        let mut __taf91 = std::mem::take(&mut __gs.t__x1);
        let mut __taf92 = std::mem::take(&mut __gs.t__x2);
        let mut __taf93 = std::mem::take(&mut __gs.t__x3);
        let mut __taf94 = std::mem::take(&mut __gs.t__x4);
        let mut __taf95 = std::mem::take(&mut __gs.t__y1);
        let mut __taf96 = std::mem::take(&mut __gs.t__y2);
        let mut __taf97 = std::mem::take(&mut __gs.t__y3);
        let mut __taf98 = std::mem::take(&mut __gs.t__y4);
        let mut __taf99 = std::mem::take(&mut __gs.t__z1);
        let mut __taf100 = std::mem::take(&mut __gs.t__xc);
        let mut __taf101 = std::mem::take(&mut __gs.t__yc);
        let mut __taf102 = std::mem::take(&mut __gs.t__tcolor);
        let mut __saf103 = std::mem::take(&mut __gs.index);
        torusdraw(&mut __rt, &mut __gs, &mut __taf91, &mut __taf92, &mut __taf93, &mut __taf94, &mut __taf95, &mut __taf96, &mut __taf97, &mut __taf98, &mut __taf99, &mut __taf100, &mut __taf101, &mut __taf102, &mut __saf103);
        __gs.t__x1 = __taf91;
        __gs.t__x2 = __taf92;
        __gs.t__x3 = __taf93;
        __gs.t__x4 = __taf94;
        __gs.t__y1 = __taf95;
        __gs.t__y2 = __taf96;
        __gs.t__y3 = __taf97;
        __gs.t__y4 = __taf98;
        __gs.t__z1 = __taf99;
        __gs.t__xc = __taf100;
        __gs.t__yc = __taf101;
        __gs.t__tcolor = __taf102;
        __gs.index = __saf103;
        while qb_bool(qb_from_bool((__rt.inkey()).as_str() == "")) {
            let mut __tmp_num104: f64 = __gs.tor__delay;
            delay(&mut __rt, &mut __gs, &mut __tmp_num104);
            torusrotate(&mut __rt, &mut __gs, &mut qb_continue);
        }
        __rt.screen(0_f64);
    }
    __rt.quit();
    // label: VideoErr
    let __sel = __gs.bestmode;
    if __sel == vga {
        __gs.bestmode = mcga;
        __gs.available = ("12BD").to_string();
    } else if __sel == mcga {
        __gs.bestmode = ega256;
        __gs.available = ("12789").to_string();
    } else if __sel == ega256 {
        __gs.bestmode = cga;
        __gs.available = ("12").to_string();
    } else if __sel == cga {
        __gs.bestmode = mono;
        __gs.available = ("A").to_string();
    } else if __sel == mono {
        __gs.bestmode = herc;
        __gs.available = ("3").to_string();
    } else {
        __rt.println(&[qb_str(&("Sorry. Graphics not available. Can't run Torus."))]);
        __rt.quit();
    }
    __rt.error_pending = false;
    // label: EGAErr
    __gs.bestmode = ega64;
    __gs.available = ("12789").to_string();
    __rt.error_pending = false;
}
