// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

#[derive(Default)]
struct GameState {
}

fn square(__rt: &mut Runtime, __gs: &mut GameState, mut x: f64) -> f64 {
    let mut __fn_ret: f64 = Default::default();
    __fn_ret = (x * x);
    __fn_ret
}

fn greet_s(__rt: &mut Runtime, __gs: &mut GameState, name_s: &mut String) -> String {
    let mut __fn_ret: String = Default::default();
    __fn_ret = (format!("{}{}" ,format!("{}{}" ,"Hello, ",name_s),"!")).to_string();
    __fn_ret
}

fn factorial(__rt: &mut Runtime, __gs: &mut GameState, mut n: f64) -> f64 {
    let mut __fn_ret: f64 = Default::default();
    if qb_bool(qb_from_bool(n <= 1_f64)) {
        __fn_ret = 1_f64;
    } else {
        let __tmp0 = factorial(__rt, __gs, (n - 1_f64));
        __fn_ret = (n * __tmp0);
    }
    __fn_ret
}

fn main() {
    let mut __rt = Runtime::new();
    let mut __gs = GameState::default();

    let __tmp1 = square(&mut __rt, &mut __gs, 5_f64);
    __rt.println(&[qb_print_num(__tmp1)]);
    let __tmp2 = square(&mut __rt, &mut __gs, 0_f64);
    __rt.println(&[qb_print_num(__tmp2)]);
    let mut __tmp_s3: String = ("World").to_string();
    let __tmp4 = greet_s(&mut __rt, &mut __gs, &mut __tmp_s3);
    __rt.println(&[qb_str(&(__tmp4))]);
    let __tmp5 = factorial(&mut __rt, &mut __gs, 5_f64);
    __rt.println(&[qb_print_num(__tmp5)]);
    let __tmp6 = factorial(&mut __rt, &mut __gs, 1_f64);
    __rt.println(&[qb_print_num(__tmp6)]);
    __rt.println(&[qb_str(&("done"))]);
}
