// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

#[derive(Default)]
struct GameState {
    result: f64,
    x: f64,
    y: f64,
}

fn addthem(__rt: &mut Runtime, __gs: &mut GameState) {
    __gs.result = (__gs.x + __gs.y);
    return;
}

fn doublex(__rt: &mut Runtime, __gs: &mut GameState) {
    __gs.x = (__gs.x * 2_f64);
    return;
}

fn main() {
    let mut __rt = Runtime::new();
    let mut __gs = GameState::default();

    __gs.x = 10_f64;
    __gs.y = 20_f64;
    addthem(&mut __rt, &mut __gs);
    __rt.println(&[qb_print_num(__gs.result)]);
    doublex(&mut __rt, &mut __gs);
    __rt.println(&[qb_print_num(__gs.x)]);
    __rt.println(&[qb_str(&("done"))]);
    __rt.quit();
}
