// Generated by qbc — QBasic to Rust transpiler
#![allow(non_snake_case, unused_variables, dead_code, unused_mut,
         unused_assignments, unused_parens, unreachable_code,
         non_upper_case_globals, const_item_mutation, clippy::all)]
use qbasic_runtime::*;

#[derive(Default)]
struct GameState {
}

fn main() {
    let mut __rt = Runtime::new();
    let mut __gs = GameState::default();

    __rt.println(&[qb_str(&("hello"))]);
    __rt.println(&[qb_str(&("a")), qb_str(&("b")), qb_str(&("c"))]);
    __rt.print(&[qb_str(&("x"))]);
    __rt.print_zone();
    __rt.println(&[qb_str(&("y"))]);
    __rt.println(&[qb_print_num(42_f64)]);
    __rt.println(&[qb_print_num((-7_f64))]);
    __rt.println(&[qb_print_num(3.14_f64)]);
    __rt.println(&[qb_str(&("n=")), qb_print_num(10_f64)]);
    __rt.println(&[]);
    __rt.println(&[qb_str(&("done"))]);
}
